
//=============================================================================
// Auto generated by Allo
//=============================================================================

// OpenCL utility layer include
#include "xcl2.hpp"
#include <algorithm>
#include <cstdio>
#include <random>
#include <vector>
#include <iomanip>
#include <fstream>


int main(int argc, char** argv) {
    if (argc != 2) {
        std::cout << "Usage: " << argv[0] << " <XCLBIN File>" << std::endl;
        return EXIT_FAILURE;
    }

    std::string binaryFile = argv[1];
    cl_int err;
    cl::CommandQueue q;
    cl::Context context;
    cl::Program program;

    cl::Kernel krnl_gemm_fp32;

    // Allocate Memory in Host Memory
    // When creating a buffer with user pointer (CL_MEM_USE_HOST_PTR), under the
    // hood user ptr is used if it is properly aligned. when not aligned, runtime had no choice
    // but to create its own host side buffer. So it is recommended to use this allocator if
    // user wish to create buffer using CL_MEM_USE_HOST_PTR to align user buffer to page
    // boundary. It will ensure that user buffer is used when user create Buffer/Mem object with
    // CL_MEM_USE_HOST_PTR
    std::ifstream ifile0("input0.data", std::ios::binary);
    if (!ifile0.is_open()) {
      std::cerr << "Error: Could not open input file.\n";
      return 1;
    }
    ifile0.seekg(0, std::ios::end);
    auto ifile0_size = ifile0.tellg();
    ifile0.seekg(0, std::ios::beg);
    if (ifile0_size != 256) {
      std::cerr << "Error: Invalid input file, byte number mismatch.\n";
      return 1;
    }
    std::vector<uint8_t>  source_in0(256);
    ifile0.read(reinterpret_cast<char*>(source_in0.data()), 256);
    std::ifstream ifile1("input1.data", std::ios::binary);
    if (!ifile1.is_open()) {
      std::cerr << "Error: Could not open input file.\n";
      return 1;
    }
    ifile1.seekg(0, std::ios::end);
    auto ifile1_size = ifile1.tellg();
    ifile1.seekg(0, std::ios::beg);
    if (ifile1_size != 256) {
      std::cerr << "Error: Invalid input file, byte number mismatch.\n";
      return 1;
    }
    std::vector<uint8_t>  source_in1(256);
    ifile1.read(reinterpret_cast<char*>(source_in1.data()), 256);
    std::ifstream ifile2("input2.data", std::ios::binary);
    if (!ifile2.is_open()) {
      std::cerr << "Error: Could not open input file.\n";
      return 1;
    }
    ifile2.seekg(0, std::ios::end);
    auto ifile2_size = ifile2.tellg();
    ifile2.seekg(0, std::ios::beg);
    if (ifile2_size != 256) {
      std::cerr << "Error: Invalid input file, byte number mismatch.\n";
      return 1;
    }
    std::vector<uint8_t>  source_in2(256);
    ifile2.read(reinterpret_cast<char*>(source_in2.data()), 256);
    std::ifstream ifile3("input3.data", std::ios::binary);
    if (!ifile3.is_open()) {
      std::cerr << "Error: Could not open input file.\n";
      return 1;
    }
    ifile3.seekg(0, std::ios::end);
    auto ifile3_size = ifile3.tellg();
    ifile3.seekg(0, std::ios::beg);
    if (ifile3_size != 1) {
      std::cerr << "Error: Invalid input file, byte number mismatch.\n";
      return 1;
    }
    std::vector<uint8_t>  source_in3_(1);
    ifile3.read(reinterpret_cast<char*>(source_in3_.data()), 1);
    uint8_t source_in3 = *reinterpret_cast<uint8_t*>(source_in3_.data());
    std::ifstream ifile4("input4.data", std::ios::binary);
    if (!ifile4.is_open()) {
      std::cerr << "Error: Could not open input file.\n";
      return 1;
    }
    ifile4.seekg(0, std::ios::end);
    auto ifile4_size = ifile4.tellg();
    ifile4.seekg(0, std::ios::beg);
    if (ifile4_size != 256) {
      std::cerr << "Error: Invalid input file, byte number mismatch.\n";
      return 1;
    }
    std::vector<uint8_t>  source_in4(256);
    ifile4.read(reinterpret_cast<char*>(source_in4.data()), 256);

    // OPENCL HOST CODE AREA START
    // get_xil_devices() is a utility API which will find the xilinx
    // platforms and will return list of devices connected to Xilinx platform
    auto devices = xcl::get_xil_devices();
    // read_binary_file() is a utility API which will load the binaryFile
    // and will return the pointer to file buffer.
    auto fileBuf = xcl::read_binary_file(binaryFile);
    cl::Program::Binaries bins{{fileBuf.data(), fileBuf.size()}};
    bool valid_device = false;
    for (unsigned int i = 0; i < devices.size(); i++) {
        auto device = devices[i];
        // Creating Context and Command Queue for selected Device
        OCL_CHECK(err, context = cl::Context(device, nullptr, nullptr, nullptr, &err));
        OCL_CHECK(err, q = cl::CommandQueue(context, device, CL_QUEUE_PROFILING_ENABLE, &err));
        std::cout << "Trying to program device[" << i << "]: " << device.getInfo<CL_DEVICE_NAME>() << std::endl;
        cl::Program program(context, {device}, bins, nullptr, &err);
        if (err != CL_SUCCESS) {
            std::cout << "Failed to program device[" << i << "] with xclbin file!\n";
        } else {
            std::cout << "Device[" << i << "]: program successful!\n";
            OCL_CHECK(err, krnl_gemm_fp32 = cl::Kernel(program, "gemm_fp32", &err));
            valid_device = true;
            break; // we break because we found a valid device
        }
    }
    if (!valid_device) {
        std::cout << "Failed to program any device found, exit!\n";
        exit(EXIT_FAILURE);
    }
    
    // Allocate Buffer in Global Memory
    // Buffers are allocated using CL_MEM_USE_HOST_PTR for efficient memory and
    // Device-to-host communication
    OCL_CHECK(err, cl::Buffer buffer_in0(context, CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY, 256, source_in0.data(), &err));
    OCL_CHECK(err, cl::Buffer buffer_in1(context, CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY, 256, source_in1.data(), &err));
    OCL_CHECK(err, cl::Buffer buffer_in2(context, CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY, 256, source_in2.data(), &err));
    OCL_CHECK(err, cl::Buffer buffer_in4(context, CL_MEM_USE_HOST_PTR | CL_MEM_READ_WRITE, 256, source_in4.data(), &err));

    OCL_CHECK(err, err = krnl_gemm_fp32.setArg(0, buffer_in0));
    OCL_CHECK(err, err = krnl_gemm_fp32.setArg(1, buffer_in1));
    OCL_CHECK(err, err = krnl_gemm_fp32.setArg(2, buffer_in2));
    OCL_CHECK(err, err = krnl_gemm_fp32.setArg(3, source_in3));
    OCL_CHECK(err, err = krnl_gemm_fp32.setArg(4, buffer_in4));
    // Copy input data to device global memory
    OCL_CHECK(err, err = q.enqueueMigrateMemObjects({buffer_in0, buffer_in1, buffer_in2, buffer_in4}, 0 /* 0 means from host*/));

    cl::Event event;
    uint64_t nstimestart, nstimeend;
    std::cout << "|-------------------------+-------------------------|\n"
              << "| Kernel                  |    Wall-Clock Time (ns) |\n"
              << "|-------------------------+-------------------------|\n";

    // Launch the Kernel
    OCL_CHECK(err, err = q.enqueueTask(krnl_gemm_fp32, nullptr, &event));

    // Copy Result from Device Global Memory to Host Local Memory
    OCL_CHECK(err, err = q.enqueueMigrateMemObjects({buffer_in4}, CL_MIGRATE_MEM_OBJECT_HOST));
    q.finish();
    // OpenCL Host Code Ends

    // Get the execution time
    OCL_CHECK(err, err = event.getProfilingInfo<uint64_t>(CL_PROFILING_COMMAND_START, &nstimestart));
    OCL_CHECK(err, err = event.getProfilingInfo<uint64_t>(CL_PROFILING_COMMAND_END, &nstimeend));
    auto exe_time = nstimeend - nstimestart;

    std::cout << "| " << std::left << std::setw(24) << "gemm_fp32 "
              << "|" << std::right << std::setw(24) << exe_time << " |\n";
    std::cout << "|-------------------------+-------------------------|\n";
    std::cout << "Note: Wall Clock Time is meaningful for real hardware execution "
              << "only, not for emulation.\n";
    std::cout << "Please refer to profile summary for kernel execution time for "
              << "hardware emulation.\n";
    std::cout << "Finished execution!\n\n";


    // Write the output data to files
    {
        std::ofstream ofile0;
        ofile0.open("output0.data", std::ios::binary);
        if (!ofile0) {
            std::cerr << "Failed to open output file 0!" << std::endl;
            return EXIT_FAILURE;
        }
        ofile0.write(reinterpret_cast<const char*>(source_in4.data()), 256);
        ofile0.close();
    }

    return EXIT_SUCCESS;
}
