// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gemm_fp32_gemm_fp32_Pipeline_l_outputs_u_l_v (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C_address0,
        C_ce0,
        C_q0,
        v26,
        mux_case_0231,
        mux_case_1241,
        mux_case_2251,
        mux_case_3261,
        mux_case_4271,
        mux_case_5281,
        mux_case_6291,
        mux_case_7301,
        mux_case_0166314,
        mux_case_1167324,
        mux_case_2168334,
        mux_case_3169344,
        mux_case_4170354,
        mux_case_5171364,
        mux_case_6172374,
        mux_case_7173384,
        mux_case_0175394,
        mux_case_1176404,
        mux_case_2177414,
        mux_case_3178424,
        mux_case_4179434,
        mux_case_5180444,
        mux_case_6181454,
        mux_case_7182464,
        mux_case_0184474,
        mux_case_1185484,
        mux_case_2186494,
        mux_case_3187504,
        mux_case_4188514,
        mux_case_5189524,
        mux_case_6190534,
        mux_case_7191544,
        mux_case_0193554,
        mux_case_1194564,
        mux_case_2195574,
        mux_case_3196584,
        mux_case_4197594,
        mux_case_5198604,
        mux_case_6199614,
        mux_case_7200624,
        mux_case_0202634,
        mux_case_1203644,
        mux_case_2204654,
        mux_case_3205664,
        mux_case_4206674,
        mux_case_5207684,
        mux_case_6208694,
        mux_case_7209704,
        mux_case_0211714,
        mux_case_1212724,
        mux_case_2213734,
        mux_case_3214744,
        mux_case_4215754,
        mux_case_5216764,
        mux_case_6217774,
        mux_case_7218784,
        mux_case_0220794,
        mux_case_1221804,
        mux_case_2222814,
        mux_case_3223824,
        mux_case_4224834,
        mux_case_5225844,
        mux_case_6226854,
        mux_case_7227864,
        D_address0,
        D_ce0,
        D_we0,
        D_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] C_address0;
output   C_ce0;
input  [31:0] C_q0;
input  [0:0] v26;
input  [31:0] mux_case_0231;
input  [31:0] mux_case_1241;
input  [31:0] mux_case_2251;
input  [31:0] mux_case_3261;
input  [31:0] mux_case_4271;
input  [31:0] mux_case_5281;
input  [31:0] mux_case_6291;
input  [31:0] mux_case_7301;
input  [31:0] mux_case_0166314;
input  [31:0] mux_case_1167324;
input  [31:0] mux_case_2168334;
input  [31:0] mux_case_3169344;
input  [31:0] mux_case_4170354;
input  [31:0] mux_case_5171364;
input  [31:0] mux_case_6172374;
input  [31:0] mux_case_7173384;
input  [31:0] mux_case_0175394;
input  [31:0] mux_case_1176404;
input  [31:0] mux_case_2177414;
input  [31:0] mux_case_3178424;
input  [31:0] mux_case_4179434;
input  [31:0] mux_case_5180444;
input  [31:0] mux_case_6181454;
input  [31:0] mux_case_7182464;
input  [31:0] mux_case_0184474;
input  [31:0] mux_case_1185484;
input  [31:0] mux_case_2186494;
input  [31:0] mux_case_3187504;
input  [31:0] mux_case_4188514;
input  [31:0] mux_case_5189524;
input  [31:0] mux_case_6190534;
input  [31:0] mux_case_7191544;
input  [31:0] mux_case_0193554;
input  [31:0] mux_case_1194564;
input  [31:0] mux_case_2195574;
input  [31:0] mux_case_3196584;
input  [31:0] mux_case_4197594;
input  [31:0] mux_case_5198604;
input  [31:0] mux_case_6199614;
input  [31:0] mux_case_7200624;
input  [31:0] mux_case_0202634;
input  [31:0] mux_case_1203644;
input  [31:0] mux_case_2204654;
input  [31:0] mux_case_3205664;
input  [31:0] mux_case_4206674;
input  [31:0] mux_case_5207684;
input  [31:0] mux_case_6208694;
input  [31:0] mux_case_7209704;
input  [31:0] mux_case_0211714;
input  [31:0] mux_case_1212724;
input  [31:0] mux_case_2213734;
input  [31:0] mux_case_3214744;
input  [31:0] mux_case_4215754;
input  [31:0] mux_case_5216764;
input  [31:0] mux_case_6217774;
input  [31:0] mux_case_7218784;
input  [31:0] mux_case_0220794;
input  [31:0] mux_case_1221804;
input  [31:0] mux_case_2222814;
input  [31:0] mux_case_3223824;
input  [31:0] mux_case_4224834;
input  [31:0] mux_case_5225844;
input  [31:0] mux_case_6226854;
input  [31:0] mux_case_7227864;
output  [5:0] D_address0;
output   D_ce0;
output   D_we0;
output  [31:0] D_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln73_reg_1408;
reg   [0:0] icmp_ln73_reg_1408_pp0_iter6_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln73_fu_659_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln73_reg_1408_pp0_iter1_reg;
reg   [0:0] icmp_ln73_reg_1408_pp0_iter2_reg;
reg   [0:0] icmp_ln73_reg_1408_pp0_iter3_reg;
reg   [0:0] icmp_ln73_reg_1408_pp0_iter4_reg;
reg   [0:0] icmp_ln73_reg_1408_pp0_iter5_reg;
wire   [3:0] select_ln73_fu_688_p3;
reg   [3:0] select_ln73_reg_1412;
wire   [2:0] trunc_ln73_fu_710_p1;
reg   [2:0] trunc_ln73_reg_1417;
wire   [2:0] trunc_ln74_fu_714_p1;
reg   [2:0] trunc_ln74_reg_1423;
wire   [63:0] zext_ln81_fu_750_p1;
reg   [63:0] zext_ln81_reg_1435;
reg   [63:0] zext_ln81_reg_1435_pp0_iter3_reg;
reg   [63:0] zext_ln81_reg_1435_pp0_iter4_reg;
reg   [63:0] zext_ln81_reg_1435_pp0_iter5_reg;
reg   [63:0] zext_ln81_reg_1435_pp0_iter6_reg;
reg   [63:0] zext_ln81_reg_1435_pp0_iter7_reg;
wire   [31:0] v28_fu_1003_p19;
reg   [31:0] v28_reg_1445;
reg   [31:0] v28_reg_1445_pp0_iter3_reg;
wire   [31:0] initial_fu_1046_p3;
reg   [31:0] initial_reg_1450;
wire   [31:0] grp_hf_add_f32_fu_634_ap_return;
reg   [31:0] v30_reg_1455;
wire   [31:0] bitcast_ln88_fu_1053_p1;
reg    grp_hf_add_f32_fu_634_ap_ce;
wire   [0:0] grp_hf_add_f32_fu_634_ap_ready_r;
wire    grp_hf_add_f32_fu_634_ap_ready;
reg    ap_block_pp0_stage0_11001_ignoreCallOp122;
wire    ap_block_pp0_stage0_ignoreCallOp122;
wire    ap_block_pp0_stage0;
reg   [3:0] v_fu_202;
wire   [3:0] add_ln74_fu_718_p2;
wire    ap_loop_init;
reg   [3:0] u_fu_206;
wire   [3:0] select_ln73_1_fu_702_p3;
reg   [6:0] indvar_flatten8_fu_210;
wire   [6:0] add_ln73_fu_665_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten8_load;
reg    C_ce0_local;
reg    D_we0_local;
reg    D_ce0_local;
wire   [0:0] icmp_ln74_fu_682_p2;
wire   [3:0] add_ln73_1_fu_696_p2;
wire   [5:0] zext_ln74_fu_741_p1;
wire   [5:0] tmp_9_fu_734_p3;
wire   [5:0] add_ln81_fu_744_p2;
wire   [31:0] tmp_fu_755_p17;
wire   [31:0] tmp_1_fu_786_p17;
wire   [31:0] tmp_2_fu_817_p17;
wire   [31:0] tmp_3_fu_848_p17;
wire   [31:0] tmp_4_fu_879_p17;
wire   [31:0] tmp_5_fu_910_p17;
wire   [31:0] tmp_6_fu_941_p17;
wire   [31:0] tmp_7_fu_972_p17;
wire   [31:0] tmp_fu_755_p19;
wire   [31:0] tmp_1_fu_786_p19;
wire   [31:0] tmp_2_fu_817_p19;
wire   [31:0] tmp_3_fu_848_p19;
wire   [31:0] tmp_4_fu_879_p19;
wire   [31:0] tmp_5_fu_910_p19;
wire   [31:0] tmp_6_fu_941_p19;
wire   [31:0] tmp_7_fu_972_p19;
wire   [31:0] v28_fu_1003_p17;
wire   [31:0] v27_fu_1042_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_fu_755_p1;
wire   [2:0] tmp_fu_755_p3;
wire   [2:0] tmp_fu_755_p5;
wire   [2:0] tmp_fu_755_p7;
wire  signed [2:0] tmp_fu_755_p9;
wire  signed [2:0] tmp_fu_755_p11;
wire  signed [2:0] tmp_fu_755_p13;
wire  signed [2:0] tmp_fu_755_p15;
wire   [2:0] tmp_1_fu_786_p1;
wire   [2:0] tmp_1_fu_786_p3;
wire   [2:0] tmp_1_fu_786_p5;
wire   [2:0] tmp_1_fu_786_p7;
wire  signed [2:0] tmp_1_fu_786_p9;
wire  signed [2:0] tmp_1_fu_786_p11;
wire  signed [2:0] tmp_1_fu_786_p13;
wire  signed [2:0] tmp_1_fu_786_p15;
wire   [2:0] tmp_2_fu_817_p1;
wire   [2:0] tmp_2_fu_817_p3;
wire   [2:0] tmp_2_fu_817_p5;
wire   [2:0] tmp_2_fu_817_p7;
wire  signed [2:0] tmp_2_fu_817_p9;
wire  signed [2:0] tmp_2_fu_817_p11;
wire  signed [2:0] tmp_2_fu_817_p13;
wire  signed [2:0] tmp_2_fu_817_p15;
wire   [2:0] tmp_3_fu_848_p1;
wire   [2:0] tmp_3_fu_848_p3;
wire   [2:0] tmp_3_fu_848_p5;
wire   [2:0] tmp_3_fu_848_p7;
wire  signed [2:0] tmp_3_fu_848_p9;
wire  signed [2:0] tmp_3_fu_848_p11;
wire  signed [2:0] tmp_3_fu_848_p13;
wire  signed [2:0] tmp_3_fu_848_p15;
wire   [2:0] tmp_4_fu_879_p1;
wire   [2:0] tmp_4_fu_879_p3;
wire   [2:0] tmp_4_fu_879_p5;
wire   [2:0] tmp_4_fu_879_p7;
wire  signed [2:0] tmp_4_fu_879_p9;
wire  signed [2:0] tmp_4_fu_879_p11;
wire  signed [2:0] tmp_4_fu_879_p13;
wire  signed [2:0] tmp_4_fu_879_p15;
wire   [2:0] tmp_5_fu_910_p1;
wire   [2:0] tmp_5_fu_910_p3;
wire   [2:0] tmp_5_fu_910_p5;
wire   [2:0] tmp_5_fu_910_p7;
wire  signed [2:0] tmp_5_fu_910_p9;
wire  signed [2:0] tmp_5_fu_910_p11;
wire  signed [2:0] tmp_5_fu_910_p13;
wire  signed [2:0] tmp_5_fu_910_p15;
wire   [2:0] tmp_6_fu_941_p1;
wire   [2:0] tmp_6_fu_941_p3;
wire   [2:0] tmp_6_fu_941_p5;
wire   [2:0] tmp_6_fu_941_p7;
wire  signed [2:0] tmp_6_fu_941_p9;
wire  signed [2:0] tmp_6_fu_941_p11;
wire  signed [2:0] tmp_6_fu_941_p13;
wire  signed [2:0] tmp_6_fu_941_p15;
wire   [2:0] tmp_7_fu_972_p1;
wire   [2:0] tmp_7_fu_972_p3;
wire   [2:0] tmp_7_fu_972_p5;
wire   [2:0] tmp_7_fu_972_p7;
wire  signed [2:0] tmp_7_fu_972_p9;
wire  signed [2:0] tmp_7_fu_972_p11;
wire  signed [2:0] tmp_7_fu_972_p13;
wire  signed [2:0] tmp_7_fu_972_p15;
wire   [2:0] v28_fu_1003_p1;
wire   [2:0] v28_fu_1003_p3;
wire   [2:0] v28_fu_1003_p5;
wire   [2:0] v28_fu_1003_p7;
wire  signed [2:0] v28_fu_1003_p9;
wire  signed [2:0] v28_fu_1003_p11;
wire  signed [2:0] v28_fu_1003_p13;
wire  signed [2:0] v28_fu_1003_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 v_fu_202 = 4'd0;
#0 u_fu_206 = 4'd0;
#0 indvar_flatten8_fu_210 = 7'd0;
#0 ap_done_reg = 1'b0;
end

hf_add_f32 grp_hf_add_f32_fu_634(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_hf_add_f32_fu_634_ap_ce),
    .a(v28_reg_1445_pp0_iter3_reg),
    .b(initial_reg_1450),
    .ap_ready(grp_hf_add_f32_fu_634_ap_ready_r),
    .result(grp_hf_add_f32_fu_634_ap_return)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U73(
    .din0(mux_case_0231),
    .din1(mux_case_1241),
    .din2(mux_case_2251),
    .din3(mux_case_3261),
    .din4(mux_case_4271),
    .din5(mux_case_5281),
    .din6(mux_case_6291),
    .din7(mux_case_7301),
    .def(tmp_fu_755_p17),
    .sel(trunc_ln74_reg_1423),
    .dout(tmp_fu_755_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U74(
    .din0(mux_case_0166314),
    .din1(mux_case_1167324),
    .din2(mux_case_2168334),
    .din3(mux_case_3169344),
    .din4(mux_case_4170354),
    .din5(mux_case_5171364),
    .din6(mux_case_6172374),
    .din7(mux_case_7173384),
    .def(tmp_1_fu_786_p17),
    .sel(trunc_ln74_reg_1423),
    .dout(tmp_1_fu_786_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U75(
    .din0(mux_case_0175394),
    .din1(mux_case_1176404),
    .din2(mux_case_2177414),
    .din3(mux_case_3178424),
    .din4(mux_case_4179434),
    .din5(mux_case_5180444),
    .din6(mux_case_6181454),
    .din7(mux_case_7182464),
    .def(tmp_2_fu_817_p17),
    .sel(trunc_ln74_reg_1423),
    .dout(tmp_2_fu_817_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U76(
    .din0(mux_case_0184474),
    .din1(mux_case_1185484),
    .din2(mux_case_2186494),
    .din3(mux_case_3187504),
    .din4(mux_case_4188514),
    .din5(mux_case_5189524),
    .din6(mux_case_6190534),
    .din7(mux_case_7191544),
    .def(tmp_3_fu_848_p17),
    .sel(trunc_ln74_reg_1423),
    .dout(tmp_3_fu_848_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U77(
    .din0(mux_case_0193554),
    .din1(mux_case_1194564),
    .din2(mux_case_2195574),
    .din3(mux_case_3196584),
    .din4(mux_case_4197594),
    .din5(mux_case_5198604),
    .din6(mux_case_6199614),
    .din7(mux_case_7200624),
    .def(tmp_4_fu_879_p17),
    .sel(trunc_ln74_reg_1423),
    .dout(tmp_4_fu_879_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U78(
    .din0(mux_case_0202634),
    .din1(mux_case_1203644),
    .din2(mux_case_2204654),
    .din3(mux_case_3205664),
    .din4(mux_case_4206674),
    .din5(mux_case_5207684),
    .din6(mux_case_6208694),
    .din7(mux_case_7209704),
    .def(tmp_5_fu_910_p17),
    .sel(trunc_ln74_reg_1423),
    .dout(tmp_5_fu_910_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U79(
    .din0(mux_case_0211714),
    .din1(mux_case_1212724),
    .din2(mux_case_2213734),
    .din3(mux_case_3214744),
    .din4(mux_case_4215754),
    .din5(mux_case_5216764),
    .din6(mux_case_6217774),
    .din7(mux_case_7218784),
    .def(tmp_6_fu_941_p17),
    .sel(trunc_ln74_reg_1423),
    .dout(tmp_6_fu_941_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U80(
    .din0(mux_case_0220794),
    .din1(mux_case_1221804),
    .din2(mux_case_2222814),
    .din3(mux_case_3223824),
    .din4(mux_case_4224834),
    .din5(mux_case_5225844),
    .din6(mux_case_6226854),
    .din7(mux_case_7227864),
    .def(tmp_7_fu_972_p17),
    .sel(trunc_ln74_reg_1423),
    .dout(tmp_7_fu_972_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U81(
    .din0(tmp_fu_755_p19),
    .din1(tmp_1_fu_786_p19),
    .din2(tmp_2_fu_817_p19),
    .din3(tmp_3_fu_848_p19),
    .din4(tmp_4_fu_879_p19),
    .din5(tmp_5_fu_910_p19),
    .din6(tmp_6_fu_941_p19),
    .din7(tmp_7_fu_972_p19),
    .def(v28_fu_1003_p17),
    .sel(trunc_ln73_reg_1417),
    .dout(v28_fu_1003_p19)
);

gemm_fp32_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln73_fu_659_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten8_fu_210 <= add_ln73_fu_665_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten8_fu_210 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            u_fu_206 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            u_fu_206 <= select_ln73_1_fu_702_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v_fu_202 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            v_fu_202 <= add_ln74_fu_718_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln73_reg_1408 <= icmp_ln73_fu_659_p2;
        icmp_ln73_reg_1408_pp0_iter1_reg <= icmp_ln73_reg_1408;
        select_ln73_reg_1412 <= select_ln73_fu_688_p3;
        trunc_ln73_reg_1417 <= trunc_ln73_fu_710_p1;
        trunc_ln74_reg_1423 <= trunc_ln74_fu_714_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        icmp_ln73_reg_1408_pp0_iter2_reg <= icmp_ln73_reg_1408_pp0_iter1_reg;
        icmp_ln73_reg_1408_pp0_iter3_reg <= icmp_ln73_reg_1408_pp0_iter2_reg;
        icmp_ln73_reg_1408_pp0_iter4_reg <= icmp_ln73_reg_1408_pp0_iter3_reg;
        icmp_ln73_reg_1408_pp0_iter5_reg <= icmp_ln73_reg_1408_pp0_iter4_reg;
        icmp_ln73_reg_1408_pp0_iter6_reg <= icmp_ln73_reg_1408_pp0_iter5_reg;
        initial_reg_1450 <= initial_fu_1046_p3;
        v28_reg_1445 <= v28_fu_1003_p19;
        v28_reg_1445_pp0_iter3_reg <= v28_reg_1445;
        v30_reg_1455 <= grp_hf_add_f32_fu_634_ap_return;
        zext_ln81_reg_1435[5 : 0] <= zext_ln81_fu_750_p1[5 : 0];
        zext_ln81_reg_1435_pp0_iter3_reg[5 : 0] <= zext_ln81_reg_1435[5 : 0];
        zext_ln81_reg_1435_pp0_iter4_reg[5 : 0] <= zext_ln81_reg_1435_pp0_iter3_reg[5 : 0];
        zext_ln81_reg_1435_pp0_iter5_reg[5 : 0] <= zext_ln81_reg_1435_pp0_iter4_reg[5 : 0];
        zext_ln81_reg_1435_pp0_iter6_reg[5 : 0] <= zext_ln81_reg_1435_pp0_iter5_reg[5 : 0];
        zext_ln81_reg_1435_pp0_iter7_reg[5 : 0] <= zext_ln81_reg_1435_pp0_iter6_reg[5 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_ce0_local = 1'b1;
    end else begin
        C_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1)))) begin
        D_ce0_local = 1'b1;
    end else begin
        D_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        D_we0_local = 1'b1;
    end else begin
        D_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln73_fu_659_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten8_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten8_load = indvar_flatten8_fu_210;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp122) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hf_add_f32_fu_634_ap_ce = 1'b1;
    end else begin
        grp_hf_add_f32_fu_634_ap_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_address0 = zext_ln81_fu_750_p1;

assign C_ce0 = C_ce0_local;

assign D_address0 = zext_ln81_reg_1435_pp0_iter7_reg;

assign D_ce0 = D_ce0_local;

assign D_d0 = bitcast_ln88_fu_1053_p1;

assign D_we0 = D_we0_local;

assign add_ln73_1_fu_696_p2 = (u_fu_206 + 4'd1);

assign add_ln73_fu_665_p2 = (ap_sig_allocacmp_indvar_flatten8_load + 7'd1);

assign add_ln74_fu_718_p2 = (select_ln73_fu_688_p3 + 4'd1);

assign add_ln81_fu_744_p2 = (zext_ln74_fu_741_p1 + tmp_9_fu_734_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = 1'b0;
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp122 = 1'b0;
end

assign ap_block_pp0_stage0_ignoreCallOp122 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = 1'b0;
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln88_fu_1053_p1 = v30_reg_1455;

assign icmp_ln73_fu_659_p2 = ((ap_sig_allocacmp_indvar_flatten8_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_682_p2 = ((v_fu_202 == 4'd8) ? 1'b1 : 1'b0);

assign initial_fu_1046_p3 = ((v26[0:0] == 1'b1) ? 32'd0 : v27_fu_1042_p1);

assign select_ln73_1_fu_702_p3 = ((icmp_ln74_fu_682_p2[0:0] == 1'b1) ? add_ln73_1_fu_696_p2 : u_fu_206);

assign select_ln73_fu_688_p3 = ((icmp_ln74_fu_682_p2[0:0] == 1'b1) ? 4'd0 : v_fu_202);

assign tmp_1_fu_786_p17 = 'bx;

assign tmp_2_fu_817_p17 = 'bx;

assign tmp_3_fu_848_p17 = 'bx;

assign tmp_4_fu_879_p17 = 'bx;

assign tmp_5_fu_910_p17 = 'bx;

assign tmp_6_fu_941_p17 = 'bx;

assign tmp_7_fu_972_p17 = 'bx;

assign tmp_9_fu_734_p3 = {{trunc_ln73_reg_1417}, {3'd0}};

assign tmp_fu_755_p17 = 'bx;

assign trunc_ln73_fu_710_p1 = select_ln73_1_fu_702_p3[2:0];

assign trunc_ln74_fu_714_p1 = select_ln73_fu_688_p3[2:0];

assign v27_fu_1042_p1 = C_q0;

assign v28_fu_1003_p17 = 'bx;

assign zext_ln74_fu_741_p1 = select_ln73_reg_1412;

assign zext_ln81_fu_750_p1 = add_ln81_fu_744_p2;

always @ (posedge ap_clk) begin
    zext_ln81_reg_1435[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln81_reg_1435_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln81_reg_1435_pp0_iter4_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln81_reg_1435_pp0_iter5_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln81_reg_1435_pp0_iter6_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln81_reg_1435_pp0_iter7_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //gemm_fp32_gemm_fp32_Pipeline_l_outputs_u_l_v
