// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gemm_fp32_gemm_fp32_Pipeline_l_j_back (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v9_address0,
        v9_ce0,
        v9_q0,
        empty_10,
        empty,
        mux_case_7227863_out,
        mux_case_7227863_out_ap_vld,
        mux_case_6226853_out,
        mux_case_6226853_out_ap_vld,
        mux_case_5225843_out,
        mux_case_5225843_out_ap_vld,
        mux_case_4224833_out,
        mux_case_4224833_out_ap_vld,
        mux_case_3223823_out,
        mux_case_3223823_out_ap_vld,
        mux_case_2222813_out,
        mux_case_2222813_out_ap_vld,
        mux_case_1221803_out,
        mux_case_1221803_out_ap_vld,
        mux_case_0220793_out,
        mux_case_0220793_out_ap_vld,
        mux_case_7218783_out,
        mux_case_7218783_out_ap_vld,
        mux_case_6217773_out,
        mux_case_6217773_out_ap_vld,
        mux_case_5216763_out,
        mux_case_5216763_out_ap_vld,
        mux_case_4215753_out,
        mux_case_4215753_out_ap_vld,
        mux_case_3214743_out,
        mux_case_3214743_out_ap_vld,
        mux_case_2213733_out,
        mux_case_2213733_out_ap_vld,
        mux_case_1212723_out,
        mux_case_1212723_out_ap_vld,
        mux_case_0211713_out,
        mux_case_0211713_out_ap_vld,
        mux_case_7209703_out,
        mux_case_7209703_out_ap_vld,
        mux_case_6208693_out,
        mux_case_6208693_out_ap_vld,
        mux_case_5207683_out,
        mux_case_5207683_out_ap_vld,
        mux_case_4206673_out,
        mux_case_4206673_out_ap_vld,
        mux_case_3205663_out,
        mux_case_3205663_out_ap_vld,
        mux_case_2204653_out,
        mux_case_2204653_out_ap_vld,
        mux_case_1203643_out,
        mux_case_1203643_out_ap_vld,
        mux_case_0202633_out,
        mux_case_0202633_out_ap_vld,
        mux_case_7200623_out,
        mux_case_7200623_out_ap_vld,
        mux_case_6199613_out,
        mux_case_6199613_out_ap_vld,
        mux_case_5198603_out,
        mux_case_5198603_out_ap_vld,
        mux_case_4197593_out,
        mux_case_4197593_out_ap_vld,
        mux_case_3196583_out,
        mux_case_3196583_out_ap_vld,
        mux_case_2195573_out,
        mux_case_2195573_out_ap_vld,
        mux_case_1194563_out,
        mux_case_1194563_out_ap_vld,
        mux_case_0193553_out,
        mux_case_0193553_out_ap_vld,
        mux_case_7191543_out,
        mux_case_7191543_out_ap_vld,
        mux_case_6190533_out,
        mux_case_6190533_out_ap_vld,
        mux_case_5189523_out,
        mux_case_5189523_out_ap_vld,
        mux_case_4188513_out,
        mux_case_4188513_out_ap_vld,
        mux_case_3187503_out,
        mux_case_3187503_out_ap_vld,
        mux_case_2186493_out,
        mux_case_2186493_out_ap_vld,
        mux_case_1185483_out,
        mux_case_1185483_out_ap_vld,
        mux_case_0184473_out,
        mux_case_0184473_out_ap_vld,
        mux_case_7182463_out,
        mux_case_7182463_out_ap_vld,
        mux_case_6181453_out,
        mux_case_6181453_out_ap_vld,
        mux_case_5180443_out,
        mux_case_5180443_out_ap_vld,
        mux_case_4179433_out,
        mux_case_4179433_out_ap_vld,
        mux_case_3178423_out,
        mux_case_3178423_out_ap_vld,
        mux_case_2177413_out,
        mux_case_2177413_out_ap_vld,
        mux_case_1176403_out,
        mux_case_1176403_out_ap_vld,
        mux_case_0175393_out,
        mux_case_0175393_out_ap_vld,
        mux_case_7173383_out,
        mux_case_7173383_out_ap_vld,
        mux_case_6172373_out,
        mux_case_6172373_out_ap_vld,
        mux_case_5171363_out,
        mux_case_5171363_out_ap_vld,
        mux_case_4170353_out,
        mux_case_4170353_out_ap_vld,
        mux_case_3169343_out,
        mux_case_3169343_out_ap_vld,
        mux_case_2168333_out,
        mux_case_2168333_out_ap_vld,
        mux_case_1167323_out,
        mux_case_1167323_out_ap_vld,
        mux_case_0166313_out,
        mux_case_0166313_out_ap_vld,
        mux_case_7302_out,
        mux_case_7302_out_ap_vld,
        mux_case_6292_out,
        mux_case_6292_out_ap_vld,
        mux_case_5282_out,
        mux_case_5282_out_ap_vld,
        mux_case_4272_out,
        mux_case_4272_out_ap_vld,
        mux_case_3262_out,
        mux_case_3262_out_ap_vld,
        mux_case_2252_out,
        mux_case_2252_out_ap_vld,
        mux_case_1242_out,
        mux_case_1242_out_ap_vld,
        mux_case_0232_out,
        mux_case_0232_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] v9_address0;
output   v9_ce0;
input  [31:0] v9_q0;
input  [2:0] empty_10;
input  [0:0] empty;
output  [31:0] mux_case_7227863_out;
output   mux_case_7227863_out_ap_vld;
output  [31:0] mux_case_6226853_out;
output   mux_case_6226853_out_ap_vld;
output  [31:0] mux_case_5225843_out;
output   mux_case_5225843_out_ap_vld;
output  [31:0] mux_case_4224833_out;
output   mux_case_4224833_out_ap_vld;
output  [31:0] mux_case_3223823_out;
output   mux_case_3223823_out_ap_vld;
output  [31:0] mux_case_2222813_out;
output   mux_case_2222813_out_ap_vld;
output  [31:0] mux_case_1221803_out;
output   mux_case_1221803_out_ap_vld;
output  [31:0] mux_case_0220793_out;
output   mux_case_0220793_out_ap_vld;
output  [31:0] mux_case_7218783_out;
output   mux_case_7218783_out_ap_vld;
output  [31:0] mux_case_6217773_out;
output   mux_case_6217773_out_ap_vld;
output  [31:0] mux_case_5216763_out;
output   mux_case_5216763_out_ap_vld;
output  [31:0] mux_case_4215753_out;
output   mux_case_4215753_out_ap_vld;
output  [31:0] mux_case_3214743_out;
output   mux_case_3214743_out_ap_vld;
output  [31:0] mux_case_2213733_out;
output   mux_case_2213733_out_ap_vld;
output  [31:0] mux_case_1212723_out;
output   mux_case_1212723_out_ap_vld;
output  [31:0] mux_case_0211713_out;
output   mux_case_0211713_out_ap_vld;
output  [31:0] mux_case_7209703_out;
output   mux_case_7209703_out_ap_vld;
output  [31:0] mux_case_6208693_out;
output   mux_case_6208693_out_ap_vld;
output  [31:0] mux_case_5207683_out;
output   mux_case_5207683_out_ap_vld;
output  [31:0] mux_case_4206673_out;
output   mux_case_4206673_out_ap_vld;
output  [31:0] mux_case_3205663_out;
output   mux_case_3205663_out_ap_vld;
output  [31:0] mux_case_2204653_out;
output   mux_case_2204653_out_ap_vld;
output  [31:0] mux_case_1203643_out;
output   mux_case_1203643_out_ap_vld;
output  [31:0] mux_case_0202633_out;
output   mux_case_0202633_out_ap_vld;
output  [31:0] mux_case_7200623_out;
output   mux_case_7200623_out_ap_vld;
output  [31:0] mux_case_6199613_out;
output   mux_case_6199613_out_ap_vld;
output  [31:0] mux_case_5198603_out;
output   mux_case_5198603_out_ap_vld;
output  [31:0] mux_case_4197593_out;
output   mux_case_4197593_out_ap_vld;
output  [31:0] mux_case_3196583_out;
output   mux_case_3196583_out_ap_vld;
output  [31:0] mux_case_2195573_out;
output   mux_case_2195573_out_ap_vld;
output  [31:0] mux_case_1194563_out;
output   mux_case_1194563_out_ap_vld;
output  [31:0] mux_case_0193553_out;
output   mux_case_0193553_out_ap_vld;
output  [31:0] mux_case_7191543_out;
output   mux_case_7191543_out_ap_vld;
output  [31:0] mux_case_6190533_out;
output   mux_case_6190533_out_ap_vld;
output  [31:0] mux_case_5189523_out;
output   mux_case_5189523_out_ap_vld;
output  [31:0] mux_case_4188513_out;
output   mux_case_4188513_out_ap_vld;
output  [31:0] mux_case_3187503_out;
output   mux_case_3187503_out_ap_vld;
output  [31:0] mux_case_2186493_out;
output   mux_case_2186493_out_ap_vld;
output  [31:0] mux_case_1185483_out;
output   mux_case_1185483_out_ap_vld;
output  [31:0] mux_case_0184473_out;
output   mux_case_0184473_out_ap_vld;
output  [31:0] mux_case_7182463_out;
output   mux_case_7182463_out_ap_vld;
output  [31:0] mux_case_6181453_out;
output   mux_case_6181453_out_ap_vld;
output  [31:0] mux_case_5180443_out;
output   mux_case_5180443_out_ap_vld;
output  [31:0] mux_case_4179433_out;
output   mux_case_4179433_out_ap_vld;
output  [31:0] mux_case_3178423_out;
output   mux_case_3178423_out_ap_vld;
output  [31:0] mux_case_2177413_out;
output   mux_case_2177413_out_ap_vld;
output  [31:0] mux_case_1176403_out;
output   mux_case_1176403_out_ap_vld;
output  [31:0] mux_case_0175393_out;
output   mux_case_0175393_out_ap_vld;
output  [31:0] mux_case_7173383_out;
output   mux_case_7173383_out_ap_vld;
output  [31:0] mux_case_6172373_out;
output   mux_case_6172373_out_ap_vld;
output  [31:0] mux_case_5171363_out;
output   mux_case_5171363_out_ap_vld;
output  [31:0] mux_case_4170353_out;
output   mux_case_4170353_out_ap_vld;
output  [31:0] mux_case_3169343_out;
output   mux_case_3169343_out_ap_vld;
output  [31:0] mux_case_2168333_out;
output   mux_case_2168333_out_ap_vld;
output  [31:0] mux_case_1167323_out;
output   mux_case_1167323_out_ap_vld;
output  [31:0] mux_case_0166313_out;
output   mux_case_0166313_out_ap_vld;
output  [31:0] mux_case_7302_out;
output   mux_case_7302_out_ap_vld;
output  [31:0] mux_case_6292_out;
output   mux_case_6292_out_ap_vld;
output  [31:0] mux_case_5282_out;
output   mux_case_5282_out_ap_vld;
output  [31:0] mux_case_4272_out;
output   mux_case_4272_out_ap_vld;
output  [31:0] mux_case_3262_out;
output   mux_case_3262_out_ap_vld;
output  [31:0] mux_case_2252_out;
output   mux_case_2252_out_ap_vld;
output  [31:0] mux_case_1242_out;
output   mux_case_1242_out_ap_vld;
output  [31:0] mux_case_0232_out;
output   mux_case_0232_out_ap_vld;

reg ap_idle;
reg mux_case_7227863_out_ap_vld;
reg mux_case_6226853_out_ap_vld;
reg mux_case_5225843_out_ap_vld;
reg mux_case_4224833_out_ap_vld;
reg mux_case_3223823_out_ap_vld;
reg mux_case_2222813_out_ap_vld;
reg mux_case_1221803_out_ap_vld;
reg mux_case_0220793_out_ap_vld;
reg mux_case_7218783_out_ap_vld;
reg mux_case_6217773_out_ap_vld;
reg mux_case_5216763_out_ap_vld;
reg mux_case_4215753_out_ap_vld;
reg mux_case_3214743_out_ap_vld;
reg mux_case_2213733_out_ap_vld;
reg mux_case_1212723_out_ap_vld;
reg mux_case_0211713_out_ap_vld;
reg mux_case_7209703_out_ap_vld;
reg mux_case_6208693_out_ap_vld;
reg mux_case_5207683_out_ap_vld;
reg mux_case_4206673_out_ap_vld;
reg mux_case_3205663_out_ap_vld;
reg mux_case_2204653_out_ap_vld;
reg mux_case_1203643_out_ap_vld;
reg mux_case_0202633_out_ap_vld;
reg mux_case_7200623_out_ap_vld;
reg mux_case_6199613_out_ap_vld;
reg mux_case_5198603_out_ap_vld;
reg mux_case_4197593_out_ap_vld;
reg mux_case_3196583_out_ap_vld;
reg mux_case_2195573_out_ap_vld;
reg mux_case_1194563_out_ap_vld;
reg mux_case_0193553_out_ap_vld;
reg mux_case_7191543_out_ap_vld;
reg mux_case_6190533_out_ap_vld;
reg mux_case_5189523_out_ap_vld;
reg mux_case_4188513_out_ap_vld;
reg mux_case_3187503_out_ap_vld;
reg mux_case_2186493_out_ap_vld;
reg mux_case_1185483_out_ap_vld;
reg mux_case_0184473_out_ap_vld;
reg mux_case_7182463_out_ap_vld;
reg mux_case_6181453_out_ap_vld;
reg mux_case_5180443_out_ap_vld;
reg mux_case_4179433_out_ap_vld;
reg mux_case_3178423_out_ap_vld;
reg mux_case_2177413_out_ap_vld;
reg mux_case_1176403_out_ap_vld;
reg mux_case_0175393_out_ap_vld;
reg mux_case_7173383_out_ap_vld;
reg mux_case_6172373_out_ap_vld;
reg mux_case_5171363_out_ap_vld;
reg mux_case_4170353_out_ap_vld;
reg mux_case_3169343_out_ap_vld;
reg mux_case_2168333_out_ap_vld;
reg mux_case_1167323_out_ap_vld;
reg mux_case_0166313_out_ap_vld;
reg mux_case_7302_out_ap_vld;
reg mux_case_6292_out_ap_vld;
reg mux_case_5282_out_ap_vld;
reg mux_case_4272_out_ap_vld;
reg mux_case_3262_out_ap_vld;
reg mux_case_2252_out_ap_vld;
reg mux_case_1242_out_ap_vld;
reg mux_case_0232_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln67_fu_213_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] tmp_1_reg_630;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] trunc_ln67_fu_230_p1;
reg   [2:0] trunc_ln67_reg_637;
wire   [63:0] zext_ln67_fu_225_p1;
wire    ap_block_pp0_stage0;
reg   [3:0] j_back_fu_176;
wire   [3:0] add_ln67_fu_219_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_back_1;
reg    v9_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_back_fu_176 = 4'd0;
#0 ap_done_reg = 1'b0;
end

gemm_fp32_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln67_fu_213_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_back_fu_176 <= add_ln67_fu_219_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_back_fu_176 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln67_reg_637 <= trunc_ln67_fu_230_p1;
    end
end

always @ (*) begin
    if (((icmp_ln67_fu_213_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_back_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_j_back_1 = j_back_fu_176;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd0) & (tmp_1_reg_630 == 3'd1))) begin
        mux_case_0166313_out_ap_vld = 1'b1;
    end else begin
        mux_case_0166313_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd0) & (tmp_1_reg_630 == 3'd2))) begin
        mux_case_0175393_out_ap_vld = 1'b1;
    end else begin
        mux_case_0175393_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd0) & (tmp_1_reg_630 == 3'd3))) begin
        mux_case_0184473_out_ap_vld = 1'b1;
    end else begin
        mux_case_0184473_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd0) & (tmp_1_reg_630 == 3'd4))) begin
        mux_case_0193553_out_ap_vld = 1'b1;
    end else begin
        mux_case_0193553_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd0) & (tmp_1_reg_630 == 3'd5))) begin
        mux_case_0202633_out_ap_vld = 1'b1;
    end else begin
        mux_case_0202633_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd0) & (tmp_1_reg_630 == 3'd6))) begin
        mux_case_0211713_out_ap_vld = 1'b1;
    end else begin
        mux_case_0211713_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd0) & (tmp_1_reg_630 == 3'd7))) begin
        mux_case_0220793_out_ap_vld = 1'b1;
    end else begin
        mux_case_0220793_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd0) & (tmp_1_reg_630 == 3'd0))) begin
        mux_case_0232_out_ap_vld = 1'b1;
    end else begin
        mux_case_0232_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd1) & (tmp_1_reg_630 == 3'd1))) begin
        mux_case_1167323_out_ap_vld = 1'b1;
    end else begin
        mux_case_1167323_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd1) & (tmp_1_reg_630 == 3'd2))) begin
        mux_case_1176403_out_ap_vld = 1'b1;
    end else begin
        mux_case_1176403_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd1) & (tmp_1_reg_630 == 3'd3))) begin
        mux_case_1185483_out_ap_vld = 1'b1;
    end else begin
        mux_case_1185483_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd1) & (tmp_1_reg_630 == 3'd4))) begin
        mux_case_1194563_out_ap_vld = 1'b1;
    end else begin
        mux_case_1194563_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd1) & (tmp_1_reg_630 == 3'd5))) begin
        mux_case_1203643_out_ap_vld = 1'b1;
    end else begin
        mux_case_1203643_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd1) & (tmp_1_reg_630 == 3'd6))) begin
        mux_case_1212723_out_ap_vld = 1'b1;
    end else begin
        mux_case_1212723_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd1) & (tmp_1_reg_630 == 3'd7))) begin
        mux_case_1221803_out_ap_vld = 1'b1;
    end else begin
        mux_case_1221803_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd1) & (tmp_1_reg_630 == 3'd0))) begin
        mux_case_1242_out_ap_vld = 1'b1;
    end else begin
        mux_case_1242_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd2) & (tmp_1_reg_630 == 3'd1))) begin
        mux_case_2168333_out_ap_vld = 1'b1;
    end else begin
        mux_case_2168333_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd2) & (tmp_1_reg_630 == 3'd2))) begin
        mux_case_2177413_out_ap_vld = 1'b1;
    end else begin
        mux_case_2177413_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd2) & (tmp_1_reg_630 == 3'd3))) begin
        mux_case_2186493_out_ap_vld = 1'b1;
    end else begin
        mux_case_2186493_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd2) & (tmp_1_reg_630 == 3'd4))) begin
        mux_case_2195573_out_ap_vld = 1'b1;
    end else begin
        mux_case_2195573_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd2) & (tmp_1_reg_630 == 3'd5))) begin
        mux_case_2204653_out_ap_vld = 1'b1;
    end else begin
        mux_case_2204653_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd2) & (tmp_1_reg_630 == 3'd6))) begin
        mux_case_2213733_out_ap_vld = 1'b1;
    end else begin
        mux_case_2213733_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd2) & (tmp_1_reg_630 == 3'd7))) begin
        mux_case_2222813_out_ap_vld = 1'b1;
    end else begin
        mux_case_2222813_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd2) & (tmp_1_reg_630 == 3'd0))) begin
        mux_case_2252_out_ap_vld = 1'b1;
    end else begin
        mux_case_2252_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd3) & (tmp_1_reg_630 == 3'd1))) begin
        mux_case_3169343_out_ap_vld = 1'b1;
    end else begin
        mux_case_3169343_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd3) & (tmp_1_reg_630 == 3'd2))) begin
        mux_case_3178423_out_ap_vld = 1'b1;
    end else begin
        mux_case_3178423_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd3) & (tmp_1_reg_630 == 3'd3))) begin
        mux_case_3187503_out_ap_vld = 1'b1;
    end else begin
        mux_case_3187503_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd3) & (tmp_1_reg_630 == 3'd4))) begin
        mux_case_3196583_out_ap_vld = 1'b1;
    end else begin
        mux_case_3196583_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd3) & (tmp_1_reg_630 == 3'd5))) begin
        mux_case_3205663_out_ap_vld = 1'b1;
    end else begin
        mux_case_3205663_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd3) & (tmp_1_reg_630 == 3'd6))) begin
        mux_case_3214743_out_ap_vld = 1'b1;
    end else begin
        mux_case_3214743_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd3) & (tmp_1_reg_630 == 3'd7))) begin
        mux_case_3223823_out_ap_vld = 1'b1;
    end else begin
        mux_case_3223823_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd3) & (tmp_1_reg_630 == 3'd0))) begin
        mux_case_3262_out_ap_vld = 1'b1;
    end else begin
        mux_case_3262_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd4) & (tmp_1_reg_630 == 3'd1))) begin
        mux_case_4170353_out_ap_vld = 1'b1;
    end else begin
        mux_case_4170353_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd4) & (tmp_1_reg_630 == 3'd2))) begin
        mux_case_4179433_out_ap_vld = 1'b1;
    end else begin
        mux_case_4179433_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd4) & (tmp_1_reg_630 == 3'd3))) begin
        mux_case_4188513_out_ap_vld = 1'b1;
    end else begin
        mux_case_4188513_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd4) & (tmp_1_reg_630 == 3'd4))) begin
        mux_case_4197593_out_ap_vld = 1'b1;
    end else begin
        mux_case_4197593_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd4) & (tmp_1_reg_630 == 3'd5))) begin
        mux_case_4206673_out_ap_vld = 1'b1;
    end else begin
        mux_case_4206673_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd4) & (tmp_1_reg_630 == 3'd6))) begin
        mux_case_4215753_out_ap_vld = 1'b1;
    end else begin
        mux_case_4215753_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd4) & (tmp_1_reg_630 == 3'd7))) begin
        mux_case_4224833_out_ap_vld = 1'b1;
    end else begin
        mux_case_4224833_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd4) & (tmp_1_reg_630 == 3'd0))) begin
        mux_case_4272_out_ap_vld = 1'b1;
    end else begin
        mux_case_4272_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd5) & (tmp_1_reg_630 == 3'd1))) begin
        mux_case_5171363_out_ap_vld = 1'b1;
    end else begin
        mux_case_5171363_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd5) & (tmp_1_reg_630 == 3'd2))) begin
        mux_case_5180443_out_ap_vld = 1'b1;
    end else begin
        mux_case_5180443_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd5) & (tmp_1_reg_630 == 3'd3))) begin
        mux_case_5189523_out_ap_vld = 1'b1;
    end else begin
        mux_case_5189523_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd5) & (tmp_1_reg_630 == 3'd4))) begin
        mux_case_5198603_out_ap_vld = 1'b1;
    end else begin
        mux_case_5198603_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd5) & (tmp_1_reg_630 == 3'd5))) begin
        mux_case_5207683_out_ap_vld = 1'b1;
    end else begin
        mux_case_5207683_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd5) & (tmp_1_reg_630 == 3'd6))) begin
        mux_case_5216763_out_ap_vld = 1'b1;
    end else begin
        mux_case_5216763_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd5) & (tmp_1_reg_630 == 3'd7))) begin
        mux_case_5225843_out_ap_vld = 1'b1;
    end else begin
        mux_case_5225843_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd5) & (tmp_1_reg_630 == 3'd0))) begin
        mux_case_5282_out_ap_vld = 1'b1;
    end else begin
        mux_case_5282_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd6) & (tmp_1_reg_630 == 3'd1))) begin
        mux_case_6172373_out_ap_vld = 1'b1;
    end else begin
        mux_case_6172373_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd6) & (tmp_1_reg_630 == 3'd2))) begin
        mux_case_6181453_out_ap_vld = 1'b1;
    end else begin
        mux_case_6181453_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd6) & (tmp_1_reg_630 == 3'd3))) begin
        mux_case_6190533_out_ap_vld = 1'b1;
    end else begin
        mux_case_6190533_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd6) & (tmp_1_reg_630 == 3'd4))) begin
        mux_case_6199613_out_ap_vld = 1'b1;
    end else begin
        mux_case_6199613_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd6) & (tmp_1_reg_630 == 3'd5))) begin
        mux_case_6208693_out_ap_vld = 1'b1;
    end else begin
        mux_case_6208693_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd6) & (tmp_1_reg_630 == 3'd6))) begin
        mux_case_6217773_out_ap_vld = 1'b1;
    end else begin
        mux_case_6217773_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd6) & (tmp_1_reg_630 == 3'd7))) begin
        mux_case_6226853_out_ap_vld = 1'b1;
    end else begin
        mux_case_6226853_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd6) & (tmp_1_reg_630 == 3'd0))) begin
        mux_case_6292_out_ap_vld = 1'b1;
    end else begin
        mux_case_6292_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd7) & (tmp_1_reg_630 == 3'd1))) begin
        mux_case_7173383_out_ap_vld = 1'b1;
    end else begin
        mux_case_7173383_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd7) & (tmp_1_reg_630 == 3'd2))) begin
        mux_case_7182463_out_ap_vld = 1'b1;
    end else begin
        mux_case_7182463_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd7) & (tmp_1_reg_630 == 3'd3))) begin
        mux_case_7191543_out_ap_vld = 1'b1;
    end else begin
        mux_case_7191543_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd7) & (tmp_1_reg_630 == 3'd4))) begin
        mux_case_7200623_out_ap_vld = 1'b1;
    end else begin
        mux_case_7200623_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd7) & (tmp_1_reg_630 == 3'd5))) begin
        mux_case_7209703_out_ap_vld = 1'b1;
    end else begin
        mux_case_7209703_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd7) & (tmp_1_reg_630 == 3'd6))) begin
        mux_case_7218783_out_ap_vld = 1'b1;
    end else begin
        mux_case_7218783_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd7) & (tmp_1_reg_630 == 3'd7))) begin
        mux_case_7227863_out_ap_vld = 1'b1;
    end else begin
        mux_case_7227863_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln67_reg_637 == 3'd7) & (tmp_1_reg_630 == 3'd0))) begin
        mux_case_7302_out_ap_vld = 1'b1;
    end else begin
        mux_case_7302_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v9_ce0_local = 1'b1;
    end else begin
        v9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_fu_219_p2 = (ap_sig_allocacmp_j_back_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln67_fu_213_p2 = ((ap_sig_allocacmp_j_back_1 == 4'd8) ? 1'b1 : 1'b0);

assign mux_case_0166313_out = v9_q0;

assign mux_case_0175393_out = v9_q0;

assign mux_case_0184473_out = v9_q0;

assign mux_case_0193553_out = v9_q0;

assign mux_case_0202633_out = v9_q0;

assign mux_case_0211713_out = v9_q0;

assign mux_case_0220793_out = v9_q0;

assign mux_case_0232_out = v9_q0;

assign mux_case_1167323_out = v9_q0;

assign mux_case_1176403_out = v9_q0;

assign mux_case_1185483_out = v9_q0;

assign mux_case_1194563_out = v9_q0;

assign mux_case_1203643_out = v9_q0;

assign mux_case_1212723_out = v9_q0;

assign mux_case_1221803_out = v9_q0;

assign mux_case_1242_out = v9_q0;

assign mux_case_2168333_out = v9_q0;

assign mux_case_2177413_out = v9_q0;

assign mux_case_2186493_out = v9_q0;

assign mux_case_2195573_out = v9_q0;

assign mux_case_2204653_out = v9_q0;

assign mux_case_2213733_out = v9_q0;

assign mux_case_2222813_out = v9_q0;

assign mux_case_2252_out = v9_q0;

assign mux_case_3169343_out = v9_q0;

assign mux_case_3178423_out = v9_q0;

assign mux_case_3187503_out = v9_q0;

assign mux_case_3196583_out = v9_q0;

assign mux_case_3205663_out = v9_q0;

assign mux_case_3214743_out = v9_q0;

assign mux_case_3223823_out = v9_q0;

assign mux_case_3262_out = v9_q0;

assign mux_case_4170353_out = v9_q0;

assign mux_case_4179433_out = v9_q0;

assign mux_case_4188513_out = v9_q0;

assign mux_case_4197593_out = v9_q0;

assign mux_case_4206673_out = v9_q0;

assign mux_case_4215753_out = v9_q0;

assign mux_case_4224833_out = v9_q0;

assign mux_case_4272_out = v9_q0;

assign mux_case_5171363_out = v9_q0;

assign mux_case_5180443_out = v9_q0;

assign mux_case_5189523_out = v9_q0;

assign mux_case_5198603_out = v9_q0;

assign mux_case_5207683_out = v9_q0;

assign mux_case_5216763_out = v9_q0;

assign mux_case_5225843_out = v9_q0;

assign mux_case_5282_out = v9_q0;

assign mux_case_6172373_out = v9_q0;

assign mux_case_6181453_out = v9_q0;

assign mux_case_6190533_out = v9_q0;

assign mux_case_6199613_out = v9_q0;

assign mux_case_6208693_out = v9_q0;

assign mux_case_6217773_out = v9_q0;

assign mux_case_6226853_out = v9_q0;

assign mux_case_6292_out = v9_q0;

assign mux_case_7173383_out = v9_q0;

assign mux_case_7182463_out = v9_q0;

assign mux_case_7191543_out = v9_q0;

assign mux_case_7200623_out = v9_q0;

assign mux_case_7209703_out = v9_q0;

assign mux_case_7218783_out = v9_q0;

assign mux_case_7227863_out = v9_q0;

assign mux_case_7302_out = v9_q0;

assign tmp_1_reg_630 = empty_10;

assign trunc_ln67_fu_230_p1 = ap_sig_allocacmp_j_back_1[2:0];

assign v9_address0 = zext_ln67_fu_225_p1;

assign v9_ce0 = v9_ce0_local;

assign zext_ln67_fu_225_p1 = ap_sig_allocacmp_j_back_1;

endmodule //gemm_fp32_gemm_fp32_Pipeline_l_j_back
