// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gemm_fp32_gemm_fp32,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=900,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2837,HLS_SYN_LUT=1778,HLS_VERSION=2024_1}" *)

module gemm_fp32 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        BT_address0,
        BT_ce0,
        BT_q0,
        C_address0,
        C_ce0,
        C_q0,
        use_c,
        D_address0,
        D_ce0,
        D_we0,
        D_d0
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [5:0] BT_address0;
output   BT_ce0;
input  [31:0] BT_q0;
output  [5:0] C_address0;
output   C_ce0;
input  [31:0] C_q0;
input  [7:0] use_c;
output  [5:0] D_address0;
output   D_ce0;
output   D_we0;
output  [31:0] D_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] i_1_reg_1581;
wire    ap_CS_fsm_state2;
wire   [0:0] v26_fu_1098_p2;
reg   [0:0] v26_reg_1910;
wire   [2:0] trunc_ln45_fu_1104_p1;
reg   [2:0] trunc_ln45_reg_1915;
wire    ap_CS_fsm_state4;
wire   [5:0] tmp_s_fu_1107_p3;
reg   [5:0] tmp_s_reg_1920;
wire   [0:0] empty_fu_1116_p2;
reg   [0:0] empty_reg_1925;
reg   [2:0] v9_address0;
reg    v9_ce0;
reg    v9_we0;
reg   [31:0] v9_d0;
wire   [31:0] v9_q0;
reg    v9_ce1;
wire   [31:0] v9_q1;
wire    grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_start;
wire    grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_done;
wire    grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_idle;
wire    grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_ready;
wire   [2:0] grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_address0;
wire    grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_ce0;
wire    grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_we0;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_d0;
wire    grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_start;
wire    grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_done;
wire    grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_idle;
wire    grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_ready;
wire   [5:0] grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_C_address0;
wire    grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_C_ce0;
wire   [5:0] grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_address0;
wire    grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_ce0;
wire    grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_we0;
wire   [31:0] grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_d0;
wire    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_start;
wire    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_done;
wire    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_idle;
wire    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_ready;
wire   [5:0] grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_BT_address0;
wire    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_BT_ce0;
wire   [2:0] grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_address0;
wire    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_ce0;
wire    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_we0;
wire   [31:0] grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_d0;
wire   [2:0] grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_address1;
wire    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_ce1;
wire   [5:0] grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_A_address0;
wire    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_A_ce0;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_start;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_done;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_idle;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_ready;
wire   [2:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_v9_address0;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_v9_ce0;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7227863_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7227863_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6226853_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6226853_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5225843_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5225843_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4224833_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4224833_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3223823_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3223823_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2222813_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2222813_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1221803_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1221803_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0220793_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0220793_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7218783_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7218783_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6217773_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6217773_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5216763_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5216763_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4215753_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4215753_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3214743_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3214743_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2213733_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2213733_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1212723_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1212723_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0211713_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0211713_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7209703_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7209703_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6208693_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6208693_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5207683_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5207683_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4206673_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4206673_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3205663_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3205663_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2204653_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2204653_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1203643_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1203643_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0202633_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0202633_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7200623_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7200623_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6199613_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6199613_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5198603_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5198603_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4197593_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4197593_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3196583_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3196583_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2195573_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2195573_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1194563_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1194563_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0193553_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0193553_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7191543_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7191543_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6190533_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6190533_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5189523_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5189523_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4188513_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4188513_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3187503_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3187503_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2186493_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2186493_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1185483_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1185483_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0184473_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0184473_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7182463_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7182463_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6181453_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6181453_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5180443_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5180443_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4179433_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4179433_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3178423_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3178423_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2177413_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2177413_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1176403_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1176403_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0175393_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0175393_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7173383_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7173383_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6172373_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6172373_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5171363_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5171363_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4170353_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4170353_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3169343_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3169343_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2168333_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2168333_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1167323_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1167323_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0166313_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0166313_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7302_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7302_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6292_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6292_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5282_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5282_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4272_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4272_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3262_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3262_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2252_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2252_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1242_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1242_out_ap_vld;
wire   [31:0] grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0232_out;
wire    grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0232_out_ap_vld;
reg    grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_start_reg;
wire   [0:0] icmp_ln45_fu_825_p2;
wire    ap_CS_fsm_state3;
reg    grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [31:0] mux_case_7227864_fu_324;
reg   [31:0] mux_case_6226854_fu_320;
reg   [31:0] mux_case_5225844_fu_316;
reg   [31:0] mux_case_4224834_fu_312;
reg   [31:0] mux_case_3223824_fu_308;
reg   [31:0] mux_case_2222814_fu_304;
reg   [31:0] mux_case_1221804_fu_300;
reg   [31:0] mux_case_0220794_fu_296;
reg   [31:0] mux_case_7218784_fu_292;
reg   [31:0] mux_case_6217774_fu_288;
reg   [31:0] mux_case_5216764_fu_284;
reg   [31:0] mux_case_4215754_fu_280;
reg   [31:0] mux_case_3214744_fu_276;
reg   [31:0] mux_case_2213734_fu_272;
reg   [31:0] mux_case_1212724_fu_268;
reg   [31:0] mux_case_0211714_fu_264;
reg   [31:0] mux_case_7209704_fu_260;
reg   [31:0] mux_case_6208694_fu_256;
reg   [31:0] mux_case_5207684_fu_252;
reg   [31:0] mux_case_4206674_fu_248;
reg   [31:0] mux_case_3205664_fu_244;
reg   [31:0] mux_case_2204654_fu_240;
reg   [31:0] mux_case_1203644_fu_236;
reg   [31:0] mux_case_0202634_fu_232;
reg   [31:0] mux_case_7200624_fu_228;
reg   [31:0] mux_case_6199614_fu_224;
reg   [31:0] mux_case_5198604_fu_220;
reg   [31:0] mux_case_4197594_fu_216;
reg   [31:0] mux_case_3196584_fu_212;
reg   [31:0] mux_case_2195574_fu_208;
reg   [31:0] mux_case_1194564_fu_204;
reg   [31:0] mux_case_0193554_fu_200;
reg   [31:0] mux_case_7191544_fu_196;
reg   [31:0] mux_case_6190534_fu_192;
reg   [31:0] mux_case_5189524_fu_188;
reg   [31:0] mux_case_4188514_fu_184;
reg   [31:0] mux_case_3187504_fu_180;
reg   [31:0] mux_case_2186494_fu_176;
reg   [31:0] mux_case_1185484_fu_172;
reg   [31:0] mux_case_0184474_fu_168;
reg   [31:0] mux_case_7182464_fu_164;
reg   [31:0] mux_case_6181454_fu_160;
reg   [31:0] mux_case_5180444_fu_156;
reg   [31:0] mux_case_4179434_fu_152;
reg   [31:0] mux_case_3178424_fu_148;
reg   [31:0] mux_case_2177414_fu_144;
reg   [31:0] mux_case_1176404_fu_140;
reg   [31:0] mux_case_0175394_fu_136;
reg   [31:0] mux_case_7173384_fu_132;
reg   [31:0] mux_case_6172374_fu_128;
reg   [31:0] mux_case_5171364_fu_124;
reg   [31:0] mux_case_4170354_fu_120;
reg   [31:0] mux_case_3169344_fu_116;
reg   [31:0] mux_case_2168334_fu_112;
reg   [31:0] mux_case_1167324_fu_108;
reg   [31:0] mux_case_0166314_fu_104;
reg   [31:0] mux_case_7301_fu_100;
reg   [31:0] mux_case_6291_fu_96;
reg   [31:0] mux_case_5281_fu_92;
reg   [31:0] mux_case_4271_fu_88;
reg   [31:0] mux_case_3261_fu_84;
reg   [31:0] mux_case_2251_fu_80;
reg   [31:0] mux_case_1241_fu_76;
reg   [31:0] mux_case_0231_fu_72;
reg   [3:0] i_fu_68;
wire   [3:0] add_ln45_fu_831_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_start_reg = 1'b0;
#0 grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_start_reg = 1'b0;
#0 grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_start_reg = 1'b0;
#0 grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_start_reg = 1'b0;
#0 mux_case_7227864_fu_324 = 32'd0;
#0 mux_case_6226854_fu_320 = 32'd0;
#0 mux_case_5225844_fu_316 = 32'd0;
#0 mux_case_4224834_fu_312 = 32'd0;
#0 mux_case_3223824_fu_308 = 32'd0;
#0 mux_case_2222814_fu_304 = 32'd0;
#0 mux_case_1221804_fu_300 = 32'd0;
#0 mux_case_0220794_fu_296 = 32'd0;
#0 mux_case_7218784_fu_292 = 32'd0;
#0 mux_case_6217774_fu_288 = 32'd0;
#0 mux_case_5216764_fu_284 = 32'd0;
#0 mux_case_4215754_fu_280 = 32'd0;
#0 mux_case_3214744_fu_276 = 32'd0;
#0 mux_case_2213734_fu_272 = 32'd0;
#0 mux_case_1212724_fu_268 = 32'd0;
#0 mux_case_0211714_fu_264 = 32'd0;
#0 mux_case_7209704_fu_260 = 32'd0;
#0 mux_case_6208694_fu_256 = 32'd0;
#0 mux_case_5207684_fu_252 = 32'd0;
#0 mux_case_4206674_fu_248 = 32'd0;
#0 mux_case_3205664_fu_244 = 32'd0;
#0 mux_case_2204654_fu_240 = 32'd0;
#0 mux_case_1203644_fu_236 = 32'd0;
#0 mux_case_0202634_fu_232 = 32'd0;
#0 mux_case_7200624_fu_228 = 32'd0;
#0 mux_case_6199614_fu_224 = 32'd0;
#0 mux_case_5198604_fu_220 = 32'd0;
#0 mux_case_4197594_fu_216 = 32'd0;
#0 mux_case_3196584_fu_212 = 32'd0;
#0 mux_case_2195574_fu_208 = 32'd0;
#0 mux_case_1194564_fu_204 = 32'd0;
#0 mux_case_0193554_fu_200 = 32'd0;
#0 mux_case_7191544_fu_196 = 32'd0;
#0 mux_case_6190534_fu_192 = 32'd0;
#0 mux_case_5189524_fu_188 = 32'd0;
#0 mux_case_4188514_fu_184 = 32'd0;
#0 mux_case_3187504_fu_180 = 32'd0;
#0 mux_case_2186494_fu_176 = 32'd0;
#0 mux_case_1185484_fu_172 = 32'd0;
#0 mux_case_0184474_fu_168 = 32'd0;
#0 mux_case_7182464_fu_164 = 32'd0;
#0 mux_case_6181454_fu_160 = 32'd0;
#0 mux_case_5180444_fu_156 = 32'd0;
#0 mux_case_4179434_fu_152 = 32'd0;
#0 mux_case_3178424_fu_148 = 32'd0;
#0 mux_case_2177414_fu_144 = 32'd0;
#0 mux_case_1176404_fu_140 = 32'd0;
#0 mux_case_0175394_fu_136 = 32'd0;
#0 mux_case_7173384_fu_132 = 32'd0;
#0 mux_case_6172374_fu_128 = 32'd0;
#0 mux_case_5171364_fu_124 = 32'd0;
#0 mux_case_4170354_fu_120 = 32'd0;
#0 mux_case_3169344_fu_116 = 32'd0;
#0 mux_case_2168334_fu_112 = 32'd0;
#0 mux_case_1167324_fu_108 = 32'd0;
#0 mux_case_0166314_fu_104 = 32'd0;
#0 mux_case_7301_fu_100 = 32'd0;
#0 mux_case_6291_fu_96 = 32'd0;
#0 mux_case_5281_fu_92 = 32'd0;
#0 mux_case_4271_fu_88 = 32'd0;
#0 mux_case_3261_fu_84 = 32'd0;
#0 mux_case_2251_fu_80 = 32'd0;
#0 mux_case_1241_fu_76 = 32'd0;
#0 mux_case_0231_fu_72 = 32'd0;
#0 i_fu_68 = 4'd0;
end

gemm_fp32_v9_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
v9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(v9_address0),
    .ce0(v9_ce0),
    .we0(v9_we0),
    .d0(v9_d0),
    .q0(v9_q0),
    .address1(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_address1),
    .ce1(v9_ce1),
    .q1(v9_q1)
);

gemm_fp32_gemm_fp32_Pipeline_l_j_init grp_gemm_fp32_Pipeline_l_j_init_fu_338(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_start),
    .ap_done(grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_done),
    .ap_idle(grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_idle),
    .ap_ready(grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_ready),
    .v9_address0(grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_address0),
    .v9_ce0(grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_ce0),
    .v9_we0(grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_we0),
    .v9_d0(grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_d0)
);

gemm_fp32_gemm_fp32_Pipeline_l_outputs_u_l_v grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_start),
    .ap_done(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_done),
    .ap_idle(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_idle),
    .ap_ready(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_ready),
    .C_address0(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_C_address0),
    .C_ce0(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_C_ce0),
    .C_q0(C_q0),
    .v26(v26_reg_1910),
    .mux_case_0231(mux_case_0231_fu_72),
    .mux_case_1241(mux_case_1241_fu_76),
    .mux_case_2251(mux_case_2251_fu_80),
    .mux_case_3261(mux_case_3261_fu_84),
    .mux_case_4271(mux_case_4271_fu_88),
    .mux_case_5281(mux_case_5281_fu_92),
    .mux_case_6291(mux_case_6291_fu_96),
    .mux_case_7301(mux_case_7301_fu_100),
    .mux_case_0166314(mux_case_0166314_fu_104),
    .mux_case_1167324(mux_case_1167324_fu_108),
    .mux_case_2168334(mux_case_2168334_fu_112),
    .mux_case_3169344(mux_case_3169344_fu_116),
    .mux_case_4170354(mux_case_4170354_fu_120),
    .mux_case_5171364(mux_case_5171364_fu_124),
    .mux_case_6172374(mux_case_6172374_fu_128),
    .mux_case_7173384(mux_case_7173384_fu_132),
    .mux_case_0175394(mux_case_0175394_fu_136),
    .mux_case_1176404(mux_case_1176404_fu_140),
    .mux_case_2177414(mux_case_2177414_fu_144),
    .mux_case_3178424(mux_case_3178424_fu_148),
    .mux_case_4179434(mux_case_4179434_fu_152),
    .mux_case_5180444(mux_case_5180444_fu_156),
    .mux_case_6181454(mux_case_6181454_fu_160),
    .mux_case_7182464(mux_case_7182464_fu_164),
    .mux_case_0184474(mux_case_0184474_fu_168),
    .mux_case_1185484(mux_case_1185484_fu_172),
    .mux_case_2186494(mux_case_2186494_fu_176),
    .mux_case_3187504(mux_case_3187504_fu_180),
    .mux_case_4188514(mux_case_4188514_fu_184),
    .mux_case_5189524(mux_case_5189524_fu_188),
    .mux_case_6190534(mux_case_6190534_fu_192),
    .mux_case_7191544(mux_case_7191544_fu_196),
    .mux_case_0193554(mux_case_0193554_fu_200),
    .mux_case_1194564(mux_case_1194564_fu_204),
    .mux_case_2195574(mux_case_2195574_fu_208),
    .mux_case_3196584(mux_case_3196584_fu_212),
    .mux_case_4197594(mux_case_4197594_fu_216),
    .mux_case_5198604(mux_case_5198604_fu_220),
    .mux_case_6199614(mux_case_6199614_fu_224),
    .mux_case_7200624(mux_case_7200624_fu_228),
    .mux_case_0202634(mux_case_0202634_fu_232),
    .mux_case_1203644(mux_case_1203644_fu_236),
    .mux_case_2204654(mux_case_2204654_fu_240),
    .mux_case_3205664(mux_case_3205664_fu_244),
    .mux_case_4206674(mux_case_4206674_fu_248),
    .mux_case_5207684(mux_case_5207684_fu_252),
    .mux_case_6208694(mux_case_6208694_fu_256),
    .mux_case_7209704(mux_case_7209704_fu_260),
    .mux_case_0211714(mux_case_0211714_fu_264),
    .mux_case_1212724(mux_case_1212724_fu_268),
    .mux_case_2213734(mux_case_2213734_fu_272),
    .mux_case_3214744(mux_case_3214744_fu_276),
    .mux_case_4215754(mux_case_4215754_fu_280),
    .mux_case_5216764(mux_case_5216764_fu_284),
    .mux_case_6217774(mux_case_6217774_fu_288),
    .mux_case_7218784(mux_case_7218784_fu_292),
    .mux_case_0220794(mux_case_0220794_fu_296),
    .mux_case_1221804(mux_case_1221804_fu_300),
    .mux_case_2222814(mux_case_2222814_fu_304),
    .mux_case_3223824(mux_case_3223824_fu_308),
    .mux_case_4224834(mux_case_4224834_fu_312),
    .mux_case_5225844(mux_case_5225844_fu_316),
    .mux_case_6226854(mux_case_6226854_fu_320),
    .mux_case_7227864(mux_case_7227864_fu_324),
    .D_address0(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_address0),
    .D_ce0(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_ce0),
    .D_we0(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_we0),
    .D_d0(grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_d0)
);

gemm_fp32_gemm_fp32_Pipeline_l_S_k_0_k_l_j grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_start),
    .ap_done(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_done),
    .ap_idle(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_idle),
    .ap_ready(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_ready),
    .BT_address0(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_BT_address0),
    .BT_ce0(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_BT_ce0),
    .BT_q0(BT_q0),
    .v9_address0(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_address0),
    .v9_ce0(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_ce0),
    .v9_we0(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_we0),
    .v9_d0(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_d0),
    .v9_address1(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_address1),
    .v9_ce1(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_ce1),
    .v9_q1(v9_q1),
    .tmp_11(tmp_s_reg_1920),
    .A_address0(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_A_address0),
    .A_ce0(grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_A_ce0),
    .A_q0(A_q0)
);

gemm_fp32_gemm_fp32_Pipeline_l_j_back grp_gemm_fp32_Pipeline_l_j_back_fu_426(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_start),
    .ap_done(grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_done),
    .ap_idle(grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_idle),
    .ap_ready(grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_ready),
    .v9_address0(grp_gemm_fp32_Pipeline_l_j_back_fu_426_v9_address0),
    .v9_ce0(grp_gemm_fp32_Pipeline_l_j_back_fu_426_v9_ce0),
    .v9_q0(v9_q0),
    .empty_10(trunc_ln45_reg_1915),
    .empty(empty_reg_1925),
    .mux_case_7227863_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7227863_out),
    .mux_case_7227863_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7227863_out_ap_vld),
    .mux_case_6226853_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6226853_out),
    .mux_case_6226853_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6226853_out_ap_vld),
    .mux_case_5225843_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5225843_out),
    .mux_case_5225843_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5225843_out_ap_vld),
    .mux_case_4224833_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4224833_out),
    .mux_case_4224833_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4224833_out_ap_vld),
    .mux_case_3223823_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3223823_out),
    .mux_case_3223823_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3223823_out_ap_vld),
    .mux_case_2222813_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2222813_out),
    .mux_case_2222813_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2222813_out_ap_vld),
    .mux_case_1221803_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1221803_out),
    .mux_case_1221803_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1221803_out_ap_vld),
    .mux_case_0220793_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0220793_out),
    .mux_case_0220793_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0220793_out_ap_vld),
    .mux_case_7218783_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7218783_out),
    .mux_case_7218783_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7218783_out_ap_vld),
    .mux_case_6217773_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6217773_out),
    .mux_case_6217773_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6217773_out_ap_vld),
    .mux_case_5216763_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5216763_out),
    .mux_case_5216763_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5216763_out_ap_vld),
    .mux_case_4215753_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4215753_out),
    .mux_case_4215753_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4215753_out_ap_vld),
    .mux_case_3214743_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3214743_out),
    .mux_case_3214743_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3214743_out_ap_vld),
    .mux_case_2213733_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2213733_out),
    .mux_case_2213733_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2213733_out_ap_vld),
    .mux_case_1212723_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1212723_out),
    .mux_case_1212723_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1212723_out_ap_vld),
    .mux_case_0211713_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0211713_out),
    .mux_case_0211713_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0211713_out_ap_vld),
    .mux_case_7209703_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7209703_out),
    .mux_case_7209703_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7209703_out_ap_vld),
    .mux_case_6208693_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6208693_out),
    .mux_case_6208693_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6208693_out_ap_vld),
    .mux_case_5207683_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5207683_out),
    .mux_case_5207683_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5207683_out_ap_vld),
    .mux_case_4206673_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4206673_out),
    .mux_case_4206673_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4206673_out_ap_vld),
    .mux_case_3205663_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3205663_out),
    .mux_case_3205663_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3205663_out_ap_vld),
    .mux_case_2204653_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2204653_out),
    .mux_case_2204653_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2204653_out_ap_vld),
    .mux_case_1203643_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1203643_out),
    .mux_case_1203643_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1203643_out_ap_vld),
    .mux_case_0202633_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0202633_out),
    .mux_case_0202633_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0202633_out_ap_vld),
    .mux_case_7200623_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7200623_out),
    .mux_case_7200623_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7200623_out_ap_vld),
    .mux_case_6199613_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6199613_out),
    .mux_case_6199613_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6199613_out_ap_vld),
    .mux_case_5198603_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5198603_out),
    .mux_case_5198603_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5198603_out_ap_vld),
    .mux_case_4197593_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4197593_out),
    .mux_case_4197593_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4197593_out_ap_vld),
    .mux_case_3196583_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3196583_out),
    .mux_case_3196583_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3196583_out_ap_vld),
    .mux_case_2195573_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2195573_out),
    .mux_case_2195573_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2195573_out_ap_vld),
    .mux_case_1194563_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1194563_out),
    .mux_case_1194563_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1194563_out_ap_vld),
    .mux_case_0193553_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0193553_out),
    .mux_case_0193553_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0193553_out_ap_vld),
    .mux_case_7191543_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7191543_out),
    .mux_case_7191543_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7191543_out_ap_vld),
    .mux_case_6190533_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6190533_out),
    .mux_case_6190533_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6190533_out_ap_vld),
    .mux_case_5189523_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5189523_out),
    .mux_case_5189523_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5189523_out_ap_vld),
    .mux_case_4188513_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4188513_out),
    .mux_case_4188513_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4188513_out_ap_vld),
    .mux_case_3187503_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3187503_out),
    .mux_case_3187503_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3187503_out_ap_vld),
    .mux_case_2186493_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2186493_out),
    .mux_case_2186493_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2186493_out_ap_vld),
    .mux_case_1185483_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1185483_out),
    .mux_case_1185483_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1185483_out_ap_vld),
    .mux_case_0184473_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0184473_out),
    .mux_case_0184473_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0184473_out_ap_vld),
    .mux_case_7182463_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7182463_out),
    .mux_case_7182463_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7182463_out_ap_vld),
    .mux_case_6181453_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6181453_out),
    .mux_case_6181453_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6181453_out_ap_vld),
    .mux_case_5180443_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5180443_out),
    .mux_case_5180443_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5180443_out_ap_vld),
    .mux_case_4179433_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4179433_out),
    .mux_case_4179433_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4179433_out_ap_vld),
    .mux_case_3178423_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3178423_out),
    .mux_case_3178423_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3178423_out_ap_vld),
    .mux_case_2177413_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2177413_out),
    .mux_case_2177413_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2177413_out_ap_vld),
    .mux_case_1176403_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1176403_out),
    .mux_case_1176403_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1176403_out_ap_vld),
    .mux_case_0175393_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0175393_out),
    .mux_case_0175393_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0175393_out_ap_vld),
    .mux_case_7173383_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7173383_out),
    .mux_case_7173383_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7173383_out_ap_vld),
    .mux_case_6172373_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6172373_out),
    .mux_case_6172373_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6172373_out_ap_vld),
    .mux_case_5171363_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5171363_out),
    .mux_case_5171363_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5171363_out_ap_vld),
    .mux_case_4170353_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4170353_out),
    .mux_case_4170353_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4170353_out_ap_vld),
    .mux_case_3169343_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3169343_out),
    .mux_case_3169343_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3169343_out_ap_vld),
    .mux_case_2168333_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2168333_out),
    .mux_case_2168333_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2168333_out_ap_vld),
    .mux_case_1167323_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1167323_out),
    .mux_case_1167323_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1167323_out_ap_vld),
    .mux_case_0166313_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0166313_out),
    .mux_case_0166313_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0166313_out_ap_vld),
    .mux_case_7302_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7302_out),
    .mux_case_7302_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7302_out_ap_vld),
    .mux_case_6292_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6292_out),
    .mux_case_6292_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6292_out_ap_vld),
    .mux_case_5282_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5282_out),
    .mux_case_5282_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5282_out_ap_vld),
    .mux_case_4272_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4272_out),
    .mux_case_4272_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4272_out_ap_vld),
    .mux_case_3262_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3262_out),
    .mux_case_3262_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3262_out_ap_vld),
    .mux_case_2252_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2252_out),
    .mux_case_2252_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2252_out_ap_vld),
    .mux_case_1242_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1242_out),
    .mux_case_1242_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1242_out_ap_vld),
    .mux_case_0232_out(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0232_out),
    .mux_case_0232_out_ap_vld(grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0232_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_start_reg <= 1'b1;
        end else if ((grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_ready == 1'b1)) begin
            grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_start_reg <= 1'b1;
        end else if ((grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_ready == 1'b1)) begin
            grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln45_fu_825_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_start_reg <= 1'b1;
        end else if ((grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_ready == 1'b1)) begin
            grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln45_fu_825_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_start_reg <= 1'b1;
        end else if ((grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_ready == 1'b1)) begin
            grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_68 <= 4'd0;
    end else if (((icmp_ln45_fu_825_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_68 <= add_ln45_fu_831_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_0166314_fu_104 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0166313_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_0166314_fu_104 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0166313_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_0175394_fu_136 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0175393_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_0175394_fu_136 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0175393_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_0184474_fu_168 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0184473_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_0184474_fu_168 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0184473_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_0193554_fu_200 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0193553_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_0193554_fu_200 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0193553_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_0202634_fu_232 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0202633_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_0202634_fu_232 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0202633_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_0211714_fu_264 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0211713_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_0211714_fu_264 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0211713_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_0220794_fu_296 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0220793_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_0220794_fu_296 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0220793_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_0231_fu_72 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0232_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_0231_fu_72 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_0232_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_1167324_fu_108 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1167323_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_1167324_fu_108 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1167323_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_1176404_fu_140 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1176403_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_1176404_fu_140 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1176403_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_1185484_fu_172 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1185483_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_1185484_fu_172 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1185483_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_1194564_fu_204 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1194563_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_1194564_fu_204 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1194563_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_1203644_fu_236 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1203643_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_1203644_fu_236 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1203643_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_1212724_fu_268 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1212723_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_1212724_fu_268 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1212723_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_1221804_fu_300 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1221803_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_1221804_fu_300 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1221803_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_1241_fu_76 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1242_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_1241_fu_76 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_1242_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_2168334_fu_112 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2168333_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_2168334_fu_112 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2168333_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_2177414_fu_144 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2177413_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_2177414_fu_144 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2177413_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_2186494_fu_176 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2186493_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_2186494_fu_176 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2186493_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_2195574_fu_208 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2195573_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_2195574_fu_208 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2195573_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_2204654_fu_240 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2204653_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_2204654_fu_240 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2204653_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_2213734_fu_272 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2213733_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_2213734_fu_272 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2213733_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_2222814_fu_304 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2222813_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_2222814_fu_304 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2222813_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_2251_fu_80 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2252_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_2251_fu_80 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_2252_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_3169344_fu_116 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3169343_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_3169344_fu_116 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3169343_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_3178424_fu_148 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3178423_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_3178424_fu_148 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3178423_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_3187504_fu_180 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3187503_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_3187504_fu_180 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3187503_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_3196584_fu_212 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3196583_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_3196584_fu_212 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3196583_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_3205664_fu_244 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3205663_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_3205664_fu_244 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3205663_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_3214744_fu_276 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3214743_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_3214744_fu_276 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3214743_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_3223824_fu_308 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3223823_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_3223824_fu_308 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3223823_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_3261_fu_84 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3262_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_3261_fu_84 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_3262_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_4170354_fu_120 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4170353_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_4170354_fu_120 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4170353_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_4179434_fu_152 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4179433_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_4179434_fu_152 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4179433_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_4188514_fu_184 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4188513_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_4188514_fu_184 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4188513_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_4197594_fu_216 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4197593_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_4197594_fu_216 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4197593_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_4206674_fu_248 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4206673_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_4206674_fu_248 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4206673_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_4215754_fu_280 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4215753_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_4215754_fu_280 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4215753_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_4224834_fu_312 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4224833_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_4224834_fu_312 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4224833_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_4271_fu_88 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4272_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_4271_fu_88 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_4272_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_5171364_fu_124 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5171363_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_5171364_fu_124 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5171363_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_5180444_fu_156 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5180443_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_5180444_fu_156 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5180443_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_5189524_fu_188 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5189523_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_5189524_fu_188 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5189523_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_5198604_fu_220 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5198603_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_5198604_fu_220 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5198603_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_5207684_fu_252 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5207683_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_5207684_fu_252 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5207683_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_5216764_fu_284 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5216763_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_5216764_fu_284 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5216763_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_5225844_fu_316 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5225843_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_5225844_fu_316 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5225843_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_5281_fu_92 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5282_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_5281_fu_92 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_5282_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_6172374_fu_128 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6172373_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_6172374_fu_128 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6172373_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_6181454_fu_160 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6181453_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_6181454_fu_160 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6181453_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_6190534_fu_192 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6190533_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_6190534_fu_192 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6190533_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_6199614_fu_224 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6199613_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_6199614_fu_224 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6199613_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_6208694_fu_256 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6208693_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_6208694_fu_256 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6208693_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_6217774_fu_288 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6217773_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_6217774_fu_288 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6217773_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_6226854_fu_320 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6226853_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_6226854_fu_320 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6226853_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_6291_fu_96 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6292_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_6291_fu_96 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_6292_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_7173384_fu_132 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7173383_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_7173384_fu_132 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7173383_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_7182464_fu_164 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7182463_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_7182464_fu_164 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7182463_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_7191544_fu_196 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7191543_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_7191544_fu_196 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7191543_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_7200624_fu_228 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7200623_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_7200624_fu_228 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7200623_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_7209704_fu_260 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7209703_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_7209704_fu_260 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7209703_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_7218784_fu_292 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7218783_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_7218784_fu_292 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7218783_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_7227864_fu_324 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7227863_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_7227864_fu_324 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7227863_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mux_case_7301_fu_100 <= 32'd0;
    end else if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7302_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        mux_case_7301_fu_100 <= grp_gemm_fp32_Pipeline_l_j_back_fu_426_mux_case_7302_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_reg_1925 <= empty_fu_1116_p2;
        tmp_s_reg_1920[5 : 3] <= tmp_s_fu_1107_p3[5 : 3];
        trunc_ln45_reg_1915 <= trunc_ln45_fu_1104_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_1581 <= i_fu_68;
        v26_reg_1910 <= v26_fu_1098_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        v9_address0 = grp_gemm_fp32_Pipeline_l_j_back_fu_426_v9_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v9_address0 = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v9_address0 = grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_address0;
    end else begin
        v9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        v9_ce0 = grp_gemm_fp32_Pipeline_l_j_back_fu_426_v9_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        v9_ce0 = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v9_ce0 = grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_ce0;
    end else begin
        v9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v9_ce1 = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_ce1;
    end else begin
        v9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v9_d0 = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v9_d0 = grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_d0;
    end else begin
        v9_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v9_we0 = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_v9_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v9_we0 = grp_gemm_fp32_Pipeline_l_j_init_fu_338_v9_we0;
    end else begin
        v9_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln45_fu_825_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_A_address0;

assign A_ce0 = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_A_ce0;

assign BT_address0 = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_BT_address0;

assign BT_ce0 = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_BT_ce0;

assign C_address0 = grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_C_address0;

assign C_ce0 = grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_C_ce0;

assign D_address0 = grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_address0;

assign D_ce0 = grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_ce0;

assign D_d0 = grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_d0;

assign D_we0 = grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_D_we0;

assign add_ln45_fu_831_p2 = (i_fu_68 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign empty_fu_1116_p2 = ((i_1_reg_1581 == 4'd7) ? 1'b1 : 1'b0);

assign grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_start = grp_gemm_fp32_Pipeline_l_S_k_0_k_l_j_fu_416_ap_start_reg;

assign grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_start = grp_gemm_fp32_Pipeline_l_j_back_fu_426_ap_start_reg;

assign grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_start = grp_gemm_fp32_Pipeline_l_j_init_fu_338_ap_start_reg;

assign grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_start = grp_gemm_fp32_Pipeline_l_outputs_u_l_v_fu_343_ap_start_reg;

assign icmp_ln45_fu_825_p2 = ((i_fu_68 == 4'd8) ? 1'b1 : 1'b0);

assign tmp_s_fu_1107_p3 = {{trunc_ln45_fu_1104_p1}, {3'd0}};

assign trunc_ln45_fu_1104_p1 = i_1_reg_1581[2:0];

assign v26_fu_1098_p2 = ((use_c == 8'd0) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp_s_reg_1920[2:0] <= 3'b000;
end

endmodule //gemm_fp32
