// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gemm_fp32_gemm_fp32_Pipeline_l_outputs_u_l_v (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RFIFONUM,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RFIFONUM,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        mux_case_0270,
        mux_case_1280,
        mux_case_2290,
        mux_case_3300,
        mux_case_4310,
        mux_case_5320,
        mux_case_6330,
        mux_case_7340,
        mux_case_0205353,
        mux_case_1206363,
        mux_case_2207373,
        mux_case_3208383,
        mux_case_4209393,
        mux_case_5210403,
        mux_case_6211413,
        mux_case_7212423,
        mux_case_0214433,
        mux_case_1215443,
        mux_case_2216453,
        mux_case_3217463,
        mux_case_4218473,
        mux_case_5219483,
        mux_case_6220493,
        mux_case_7221503,
        mux_case_0223513,
        mux_case_1224523,
        mux_case_2225533,
        mux_case_3226543,
        mux_case_4227553,
        mux_case_5228563,
        mux_case_6229573,
        mux_case_7230583,
        mux_case_0232593,
        mux_case_1233603,
        mux_case_2234613,
        mux_case_3235623,
        mux_case_4236633,
        mux_case_5237643,
        mux_case_6238653,
        mux_case_7239663,
        mux_case_0241673,
        mux_case_1242683,
        mux_case_2243693,
        mux_case_3244703,
        mux_case_4245713,
        mux_case_5246723,
        mux_case_6247733,
        mux_case_7248743,
        mux_case_0250753,
        mux_case_1251763,
        mux_case_2252773,
        mux_case_3253783,
        mux_case_4254793,
        mux_case_5255803,
        mux_case_6256813,
        mux_case_7257823,
        mux_case_0259833,
        mux_case_1260843,
        mux_case_2261853,
        mux_case_3262863,
        mux_case_4263873,
        mux_case_5264883,
        mux_case_6265893,
        mux_case_7266903,
        sext_ln70_1,
        v26,
        sext_ln70
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [63:0] m_axi_gmem2_AWADDR;
output  [0:0] m_axi_gmem2_AWID;
output  [31:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [0:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [31:0] m_axi_gmem2_WDATA;
output  [3:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [0:0] m_axi_gmem2_WID;
output  [0:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [63:0] m_axi_gmem2_ARADDR;
output  [0:0] m_axi_gmem2_ARID;
output  [31:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [0:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [31:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [0:0] m_axi_gmem2_RID;
input  [8:0] m_axi_gmem2_RFIFONUM;
input  [0:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [0:0] m_axi_gmem2_BID;
input  [0:0] m_axi_gmem2_BUSER;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [63:0] m_axi_gmem3_AWADDR;
output  [0:0] m_axi_gmem3_AWID;
output  [31:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [0:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [31:0] m_axi_gmem3_WDATA;
output  [3:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [0:0] m_axi_gmem3_WID;
output  [0:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [63:0] m_axi_gmem3_ARADDR;
output  [0:0] m_axi_gmem3_ARID;
output  [31:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [0:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [31:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [0:0] m_axi_gmem3_RID;
input  [8:0] m_axi_gmem3_RFIFONUM;
input  [0:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [0:0] m_axi_gmem3_BID;
input  [0:0] m_axi_gmem3_BUSER;
input  [31:0] mux_case_0270;
input  [31:0] mux_case_1280;
input  [31:0] mux_case_2290;
input  [31:0] mux_case_3300;
input  [31:0] mux_case_4310;
input  [31:0] mux_case_5320;
input  [31:0] mux_case_6330;
input  [31:0] mux_case_7340;
input  [31:0] mux_case_0205353;
input  [31:0] mux_case_1206363;
input  [31:0] mux_case_2207373;
input  [31:0] mux_case_3208383;
input  [31:0] mux_case_4209393;
input  [31:0] mux_case_5210403;
input  [31:0] mux_case_6211413;
input  [31:0] mux_case_7212423;
input  [31:0] mux_case_0214433;
input  [31:0] mux_case_1215443;
input  [31:0] mux_case_2216453;
input  [31:0] mux_case_3217463;
input  [31:0] mux_case_4218473;
input  [31:0] mux_case_5219483;
input  [31:0] mux_case_6220493;
input  [31:0] mux_case_7221503;
input  [31:0] mux_case_0223513;
input  [31:0] mux_case_1224523;
input  [31:0] mux_case_2225533;
input  [31:0] mux_case_3226543;
input  [31:0] mux_case_4227553;
input  [31:0] mux_case_5228563;
input  [31:0] mux_case_6229573;
input  [31:0] mux_case_7230583;
input  [31:0] mux_case_0232593;
input  [31:0] mux_case_1233603;
input  [31:0] mux_case_2234613;
input  [31:0] mux_case_3235623;
input  [31:0] mux_case_4236633;
input  [31:0] mux_case_5237643;
input  [31:0] mux_case_6238653;
input  [31:0] mux_case_7239663;
input  [31:0] mux_case_0241673;
input  [31:0] mux_case_1242683;
input  [31:0] mux_case_2243693;
input  [31:0] mux_case_3244703;
input  [31:0] mux_case_4245713;
input  [31:0] mux_case_5246723;
input  [31:0] mux_case_6247733;
input  [31:0] mux_case_7248743;
input  [31:0] mux_case_0250753;
input  [31:0] mux_case_1251763;
input  [31:0] mux_case_2252773;
input  [31:0] mux_case_3253783;
input  [31:0] mux_case_4254793;
input  [31:0] mux_case_5255803;
input  [31:0] mux_case_6256813;
input  [31:0] mux_case_7257823;
input  [31:0] mux_case_0259833;
input  [31:0] mux_case_1260843;
input  [31:0] mux_case_2261853;
input  [31:0] mux_case_3262863;
input  [31:0] mux_case_4263873;
input  [31:0] mux_case_5264883;
input  [31:0] mux_case_6265893;
input  [31:0] mux_case_7266903;
input  [61:0] sext_ln70_1;
input  [0:0] v26;
input  [61:0] sext_ln70;

reg ap_idle;
reg m_axi_gmem2_ARVALID;
reg m_axi_gmem2_RREADY;
reg m_axi_gmem3_AWVALID;
reg m_axi_gmem3_WVALID;
reg m_axi_gmem3_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln70_reg_1500;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter2_reg;
reg    ap_predicate_op146_readreq_state4;
reg    ap_block_state4_io;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter10_reg;
reg    ap_predicate_op154_read_state12;
reg    ap_block_state12_pp0_stage0_iter11;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter15_reg;
reg    ap_block_state23_pp0_stage0_iter22;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln70_fu_720_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem3_blk_n_AW;
wire    ap_block_pp0_stage0;
reg    gmem3_blk_n_W;
reg    gmem3_blk_n_B;
reg    gmem2_blk_n_AR;
reg    gmem2_blk_n_R;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] v26_read_read_fu_250_p2;
wire  signed [62:0] sext_ln70_cast_fu_694_p1;
reg  signed [62:0] sext_ln70_cast_reg_1485;
wire  signed [62:0] sext_ln70_1_cast_fu_698_p1;
reg  signed [62:0] sext_ln70_1_cast_reg_1490;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter1_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter3_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter4_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter5_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter6_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter7_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter8_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter9_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter11_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter12_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter13_reg;
reg   [0:0] icmp_ln70_reg_1500_pp0_iter14_reg;
wire   [3:0] select_ln70_fu_749_p3;
reg   [3:0] select_ln70_reg_1504;
wire   [2:0] trunc_ln70_fu_771_p1;
reg   [2:0] trunc_ln70_reg_1509;
wire   [2:0] trunc_ln71_fu_775_p1;
reg   [2:0] trunc_ln71_reg_1515;
reg   [63:0] gmem2_addr_reg_1527;
wire   [31:0] v28_fu_1078_p19;
reg   [31:0] v28_reg_1533;
reg   [31:0] v28_reg_1533_pp0_iter3_reg;
reg   [31:0] v28_reg_1533_pp0_iter4_reg;
reg   [31:0] v28_reg_1533_pp0_iter5_reg;
reg   [31:0] v28_reg_1533_pp0_iter6_reg;
reg   [31:0] v28_reg_1533_pp0_iter7_reg;
reg   [31:0] v28_reg_1533_pp0_iter8_reg;
reg   [31:0] v28_reg_1533_pp0_iter9_reg;
reg   [31:0] v28_reg_1533_pp0_iter10_reg;
reg   [31:0] v28_reg_1533_pp0_iter11_reg;
reg   [31:0] v28_reg_1533_pp0_iter12_reg;
reg   [63:0] gmem3_addr_reg_1538;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter3_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter4_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter5_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter6_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter7_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter8_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter9_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter10_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter11_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter12_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter13_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter14_reg;
reg   [63:0] gmem3_addr_reg_1538_pp0_iter15_reg;
wire   [31:0] v27_fu_1132_p1;
reg   [31:0] v27_reg_1544;
wire   [31:0] grp_hf_add_f32_fu_686_ap_return;
reg   [31:0] v30_reg_1549;
reg    grp_hf_add_f32_fu_686_ap_ce;
wire   [0:0] grp_hf_add_f32_fu_686_ap_ready_r;
wire    grp_hf_add_f32_fu_686_ap_ready;
reg    ap_block_state12_pp0_stage0_iter11_ignore_call10;
reg    ap_block_state23_pp0_stage0_iter22_ignore_call10;
reg    ap_block_pp0_stage0_11001_ignoreCallOp158;
wire   [31:0] ap_phi_reg_pp0_iter0_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter1_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter2_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter3_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter4_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter5_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter6_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter7_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter8_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter9_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter10_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter11_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter12_initial_reg_674;
reg   [31:0] ap_phi_reg_pp0_iter13_initial_reg_674;
wire    ap_block_pp0_stage0_ignoreCallOp158;
wire  signed [63:0] sext_ln78_fu_820_p1;
wire  signed [63:0] sext_ln85_fu_1122_p1;
reg    ap_block_pp0_stage0_01001;
reg   [3:0] v_fu_228;
wire   [3:0] add_ln71_fu_779_p2;
wire    ap_loop_init;
reg   [3:0] u_fu_232;
wire   [3:0] select_ln70_1_fu_763_p3;
reg   [6:0] indvar_flatten8_fu_236;
wire   [6:0] add_ln70_fu_726_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten8_load;
wire   [0:0] icmp_ln71_fu_743_p2;
wire   [3:0] add_ln70_1_fu_757_p2;
wire   [5:0] zext_ln71_fu_802_p1;
wire   [5:0] tmp_9_fu_795_p3;
wire   [5:0] add_ln77_fu_805_p2;
wire   [62:0] zext_ln77_fu_811_p1;
wire   [62:0] add_ln78_fu_815_p2;
wire   [31:0] tmp_fu_830_p17;
wire   [31:0] tmp_1_fu_861_p17;
wire   [31:0] tmp_2_fu_892_p17;
wire   [31:0] tmp_3_fu_923_p17;
wire   [31:0] tmp_4_fu_954_p17;
wire   [31:0] tmp_5_fu_985_p17;
wire   [31:0] tmp_6_fu_1016_p17;
wire   [31:0] tmp_7_fu_1047_p17;
wire   [31:0] tmp_fu_830_p19;
wire   [31:0] tmp_1_fu_861_p19;
wire   [31:0] tmp_2_fu_892_p19;
wire   [31:0] tmp_3_fu_923_p19;
wire   [31:0] tmp_4_fu_954_p19;
wire   [31:0] tmp_5_fu_985_p19;
wire   [31:0] tmp_6_fu_1016_p19;
wire   [31:0] tmp_7_fu_1047_p19;
wire   [31:0] v28_fu_1078_p17;
wire   [62:0] add_ln85_fu_1117_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_764;
wire   [2:0] tmp_fu_830_p1;
wire   [2:0] tmp_fu_830_p3;
wire   [2:0] tmp_fu_830_p5;
wire   [2:0] tmp_fu_830_p7;
wire  signed [2:0] tmp_fu_830_p9;
wire  signed [2:0] tmp_fu_830_p11;
wire  signed [2:0] tmp_fu_830_p13;
wire  signed [2:0] tmp_fu_830_p15;
wire   [2:0] tmp_1_fu_861_p1;
wire   [2:0] tmp_1_fu_861_p3;
wire   [2:0] tmp_1_fu_861_p5;
wire   [2:0] tmp_1_fu_861_p7;
wire  signed [2:0] tmp_1_fu_861_p9;
wire  signed [2:0] tmp_1_fu_861_p11;
wire  signed [2:0] tmp_1_fu_861_p13;
wire  signed [2:0] tmp_1_fu_861_p15;
wire   [2:0] tmp_2_fu_892_p1;
wire   [2:0] tmp_2_fu_892_p3;
wire   [2:0] tmp_2_fu_892_p5;
wire   [2:0] tmp_2_fu_892_p7;
wire  signed [2:0] tmp_2_fu_892_p9;
wire  signed [2:0] tmp_2_fu_892_p11;
wire  signed [2:0] tmp_2_fu_892_p13;
wire  signed [2:0] tmp_2_fu_892_p15;
wire   [2:0] tmp_3_fu_923_p1;
wire   [2:0] tmp_3_fu_923_p3;
wire   [2:0] tmp_3_fu_923_p5;
wire   [2:0] tmp_3_fu_923_p7;
wire  signed [2:0] tmp_3_fu_923_p9;
wire  signed [2:0] tmp_3_fu_923_p11;
wire  signed [2:0] tmp_3_fu_923_p13;
wire  signed [2:0] tmp_3_fu_923_p15;
wire   [2:0] tmp_4_fu_954_p1;
wire   [2:0] tmp_4_fu_954_p3;
wire   [2:0] tmp_4_fu_954_p5;
wire   [2:0] tmp_4_fu_954_p7;
wire  signed [2:0] tmp_4_fu_954_p9;
wire  signed [2:0] tmp_4_fu_954_p11;
wire  signed [2:0] tmp_4_fu_954_p13;
wire  signed [2:0] tmp_4_fu_954_p15;
wire   [2:0] tmp_5_fu_985_p1;
wire   [2:0] tmp_5_fu_985_p3;
wire   [2:0] tmp_5_fu_985_p5;
wire   [2:0] tmp_5_fu_985_p7;
wire  signed [2:0] tmp_5_fu_985_p9;
wire  signed [2:0] tmp_5_fu_985_p11;
wire  signed [2:0] tmp_5_fu_985_p13;
wire  signed [2:0] tmp_5_fu_985_p15;
wire   [2:0] tmp_6_fu_1016_p1;
wire   [2:0] tmp_6_fu_1016_p3;
wire   [2:0] tmp_6_fu_1016_p5;
wire   [2:0] tmp_6_fu_1016_p7;
wire  signed [2:0] tmp_6_fu_1016_p9;
wire  signed [2:0] tmp_6_fu_1016_p11;
wire  signed [2:0] tmp_6_fu_1016_p13;
wire  signed [2:0] tmp_6_fu_1016_p15;
wire   [2:0] tmp_7_fu_1047_p1;
wire   [2:0] tmp_7_fu_1047_p3;
wire   [2:0] tmp_7_fu_1047_p5;
wire   [2:0] tmp_7_fu_1047_p7;
wire  signed [2:0] tmp_7_fu_1047_p9;
wire  signed [2:0] tmp_7_fu_1047_p11;
wire  signed [2:0] tmp_7_fu_1047_p13;
wire  signed [2:0] tmp_7_fu_1047_p15;
wire   [2:0] v28_fu_1078_p1;
wire   [2:0] v28_fu_1078_p3;
wire   [2:0] v28_fu_1078_p5;
wire   [2:0] v28_fu_1078_p7;
wire  signed [2:0] v28_fu_1078_p9;
wire  signed [2:0] v28_fu_1078_p11;
wire  signed [2:0] v28_fu_1078_p13;
wire  signed [2:0] v28_fu_1078_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 v_fu_228 = 4'd0;
#0 u_fu_232 = 4'd0;
#0 indvar_flatten8_fu_236 = 7'd0;
#0 ap_done_reg = 1'b0;
end

hf_add_f32 grp_hf_add_f32_fu_686(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_hf_add_f32_fu_686_ap_ce),
    .a(v28_reg_1533_pp0_iter12_reg),
    .b(ap_phi_reg_pp0_iter13_initial_reg_674),
    .ap_ready(grp_hf_add_f32_fu_686_ap_ready_r),
    .result(grp_hf_add_f32_fu_686_ap_return),
    .ap_ready(grp_hf_add_f32_fu_686_ap_ready)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U74(
    .din0(mux_case_0270),
    .din1(mux_case_1280),
    .din2(mux_case_2290),
    .din3(mux_case_3300),
    .din4(mux_case_4310),
    .din5(mux_case_5320),
    .din6(mux_case_6330),
    .din7(mux_case_7340),
    .def(tmp_fu_830_p17),
    .sel(trunc_ln71_reg_1515),
    .dout(tmp_fu_830_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U75(
    .din0(mux_case_0205353),
    .din1(mux_case_1206363),
    .din2(mux_case_2207373),
    .din3(mux_case_3208383),
    .din4(mux_case_4209393),
    .din5(mux_case_5210403),
    .din6(mux_case_6211413),
    .din7(mux_case_7212423),
    .def(tmp_1_fu_861_p17),
    .sel(trunc_ln71_reg_1515),
    .dout(tmp_1_fu_861_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U76(
    .din0(mux_case_0214433),
    .din1(mux_case_1215443),
    .din2(mux_case_2216453),
    .din3(mux_case_3217463),
    .din4(mux_case_4218473),
    .din5(mux_case_5219483),
    .din6(mux_case_6220493),
    .din7(mux_case_7221503),
    .def(tmp_2_fu_892_p17),
    .sel(trunc_ln71_reg_1515),
    .dout(tmp_2_fu_892_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U77(
    .din0(mux_case_0223513),
    .din1(mux_case_1224523),
    .din2(mux_case_2225533),
    .din3(mux_case_3226543),
    .din4(mux_case_4227553),
    .din5(mux_case_5228563),
    .din6(mux_case_6229573),
    .din7(mux_case_7230583),
    .def(tmp_3_fu_923_p17),
    .sel(trunc_ln71_reg_1515),
    .dout(tmp_3_fu_923_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U78(
    .din0(mux_case_0232593),
    .din1(mux_case_1233603),
    .din2(mux_case_2234613),
    .din3(mux_case_3235623),
    .din4(mux_case_4236633),
    .din5(mux_case_5237643),
    .din6(mux_case_6238653),
    .din7(mux_case_7239663),
    .def(tmp_4_fu_954_p17),
    .sel(trunc_ln71_reg_1515),
    .dout(tmp_4_fu_954_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U79(
    .din0(mux_case_0241673),
    .din1(mux_case_1242683),
    .din2(mux_case_2243693),
    .din3(mux_case_3244703),
    .din4(mux_case_4245713),
    .din5(mux_case_5246723),
    .din6(mux_case_6247733),
    .din7(mux_case_7248743),
    .def(tmp_5_fu_985_p17),
    .sel(trunc_ln71_reg_1515),
    .dout(tmp_5_fu_985_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U80(
    .din0(mux_case_0250753),
    .din1(mux_case_1251763),
    .din2(mux_case_2252773),
    .din3(mux_case_3253783),
    .din4(mux_case_4254793),
    .din5(mux_case_5255803),
    .din6(mux_case_6256813),
    .din7(mux_case_7257823),
    .def(tmp_6_fu_1016_p17),
    .sel(trunc_ln71_reg_1515),
    .dout(tmp_6_fu_1016_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U81(
    .din0(mux_case_0259833),
    .din1(mux_case_1260843),
    .din2(mux_case_2261853),
    .din3(mux_case_3262863),
    .din4(mux_case_4263873),
    .din5(mux_case_5264883),
    .din6(mux_case_6265893),
    .din7(mux_case_7266903),
    .def(tmp_7_fu_1047_p17),
    .sel(trunc_ln71_reg_1515),
    .dout(tmp_7_fu_1047_p19)
);

(* dissolve_hierarchy = "yes" *) gemm_fp32_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U82(
    .din0(tmp_fu_830_p19),
    .din1(tmp_1_fu_861_p19),
    .din2(tmp_2_fu_892_p19),
    .din3(tmp_3_fu_923_p19),
    .din4(tmp_4_fu_954_p19),
    .din5(tmp_5_fu_985_p19),
    .din6(tmp_6_fu_1016_p19),
    .din7(tmp_7_fu_1047_p19),
    .def(v28_fu_1078_p17),
    .sel(trunc_ln70_reg_1509),
    .dout(v28_fu_1078_p19)
);

gemm_fp32_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter21_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln70_reg_1500_pp0_iter11_reg == 1'd0) & (v26 == 1'd0))) begin
            ap_phi_reg_pp0_iter13_initial_reg_674 <= v27_reg_1544;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter13_initial_reg_674 <= ap_phi_reg_pp0_iter12_initial_reg_674;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_764)) begin
        if (((v26_read_read_fu_250_p2 == 1'd1) & (icmp_ln70_fu_720_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_initial_reg_674 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_initial_reg_674 <= ap_phi_reg_pp0_iter0_initial_reg_674;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln70_fu_720_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten8_fu_236 <= add_ln70_fu_726_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten8_fu_236 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            u_fu_232 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            u_fu_232 <= select_ln70_1_fu_763_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            v_fu_228 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            v_fu_228 <= add_ln71_fu_779_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem2_addr_reg_1527 <= sext_ln78_fu_820_p1;
        gmem3_addr_reg_1538 <= sext_ln85_fu_1122_p1;
        gmem3_addr_reg_1538_pp0_iter10_reg <= gmem3_addr_reg_1538_pp0_iter9_reg;
        gmem3_addr_reg_1538_pp0_iter11_reg <= gmem3_addr_reg_1538_pp0_iter10_reg;
        gmem3_addr_reg_1538_pp0_iter12_reg <= gmem3_addr_reg_1538_pp0_iter11_reg;
        gmem3_addr_reg_1538_pp0_iter13_reg <= gmem3_addr_reg_1538_pp0_iter12_reg;
        gmem3_addr_reg_1538_pp0_iter14_reg <= gmem3_addr_reg_1538_pp0_iter13_reg;
        gmem3_addr_reg_1538_pp0_iter15_reg <= gmem3_addr_reg_1538_pp0_iter14_reg;
        gmem3_addr_reg_1538_pp0_iter3_reg <= gmem3_addr_reg_1538;
        gmem3_addr_reg_1538_pp0_iter4_reg <= gmem3_addr_reg_1538_pp0_iter3_reg;
        gmem3_addr_reg_1538_pp0_iter5_reg <= gmem3_addr_reg_1538_pp0_iter4_reg;
        gmem3_addr_reg_1538_pp0_iter6_reg <= gmem3_addr_reg_1538_pp0_iter5_reg;
        gmem3_addr_reg_1538_pp0_iter7_reg <= gmem3_addr_reg_1538_pp0_iter6_reg;
        gmem3_addr_reg_1538_pp0_iter8_reg <= gmem3_addr_reg_1538_pp0_iter7_reg;
        gmem3_addr_reg_1538_pp0_iter9_reg <= gmem3_addr_reg_1538_pp0_iter8_reg;
        icmp_ln70_reg_1500_pp0_iter10_reg <= icmp_ln70_reg_1500_pp0_iter9_reg;
        icmp_ln70_reg_1500_pp0_iter11_reg <= icmp_ln70_reg_1500_pp0_iter10_reg;
        icmp_ln70_reg_1500_pp0_iter12_reg <= icmp_ln70_reg_1500_pp0_iter11_reg;
        icmp_ln70_reg_1500_pp0_iter13_reg <= icmp_ln70_reg_1500_pp0_iter12_reg;
        icmp_ln70_reg_1500_pp0_iter14_reg <= icmp_ln70_reg_1500_pp0_iter13_reg;
        icmp_ln70_reg_1500_pp0_iter15_reg <= icmp_ln70_reg_1500_pp0_iter14_reg;
        icmp_ln70_reg_1500_pp0_iter2_reg <= icmp_ln70_reg_1500_pp0_iter1_reg;
        icmp_ln70_reg_1500_pp0_iter3_reg <= icmp_ln70_reg_1500_pp0_iter2_reg;
        icmp_ln70_reg_1500_pp0_iter4_reg <= icmp_ln70_reg_1500_pp0_iter3_reg;
        icmp_ln70_reg_1500_pp0_iter5_reg <= icmp_ln70_reg_1500_pp0_iter4_reg;
        icmp_ln70_reg_1500_pp0_iter6_reg <= icmp_ln70_reg_1500_pp0_iter5_reg;
        icmp_ln70_reg_1500_pp0_iter7_reg <= icmp_ln70_reg_1500_pp0_iter6_reg;
        icmp_ln70_reg_1500_pp0_iter8_reg <= icmp_ln70_reg_1500_pp0_iter7_reg;
        icmp_ln70_reg_1500_pp0_iter9_reg <= icmp_ln70_reg_1500_pp0_iter8_reg;
        v27_reg_1544 <= v27_fu_1132_p1;
        v28_reg_1533 <= v28_fu_1078_p19;
        v28_reg_1533_pp0_iter10_reg <= v28_reg_1533_pp0_iter9_reg;
        v28_reg_1533_pp0_iter11_reg <= v28_reg_1533_pp0_iter10_reg;
        v28_reg_1533_pp0_iter12_reg <= v28_reg_1533_pp0_iter11_reg;
        v28_reg_1533_pp0_iter3_reg <= v28_reg_1533;
        v28_reg_1533_pp0_iter4_reg <= v28_reg_1533_pp0_iter3_reg;
        v28_reg_1533_pp0_iter5_reg <= v28_reg_1533_pp0_iter4_reg;
        v28_reg_1533_pp0_iter6_reg <= v28_reg_1533_pp0_iter5_reg;
        v28_reg_1533_pp0_iter7_reg <= v28_reg_1533_pp0_iter6_reg;
        v28_reg_1533_pp0_iter8_reg <= v28_reg_1533_pp0_iter7_reg;
        v28_reg_1533_pp0_iter9_reg <= v28_reg_1533_pp0_iter8_reg;
        v30_reg_1549 <= grp_hf_add_f32_fu_686_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln70_reg_1500 <= icmp_ln70_fu_720_p2;
        icmp_ln70_reg_1500_pp0_iter1_reg <= icmp_ln70_reg_1500;
        select_ln70_reg_1504 <= select_ln70_fu_749_p3;
        sext_ln70_1_cast_reg_1490 <= sext_ln70_1_cast_fu_698_p1;
        sext_ln70_cast_reg_1485 <= sext_ln70_cast_fu_694_p1;
        trunc_ln70_reg_1509 <= trunc_ln70_fu_771_p1;
        trunc_ln71_reg_1515 <= trunc_ln71_fu_775_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_initial_reg_674 <= ap_phi_reg_pp0_iter9_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_initial_reg_674 <= ap_phi_reg_pp0_iter10_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_initial_reg_674 <= ap_phi_reg_pp0_iter11_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_initial_reg_674 <= ap_phi_reg_pp0_iter1_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_initial_reg_674 <= ap_phi_reg_pp0_iter2_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_initial_reg_674 <= ap_phi_reg_pp0_iter3_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_initial_reg_674 <= ap_phi_reg_pp0_iter4_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_initial_reg_674 <= ap_phi_reg_pp0_iter5_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_initial_reg_674 <= ap_phi_reg_pp0_iter6_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_initial_reg_674 <= ap_phi_reg_pp0_iter7_initial_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_initial_reg_674 <= ap_phi_reg_pp0_iter8_initial_reg_674;
    end
end

always @ (*) begin
    if (((icmp_ln70_fu_720_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter21_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten8_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten8_load = indvar_flatten8_fu_236;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op146_readreq_state4 == 1'b1))) begin
        gmem2_blk_n_AR = m_axi_gmem2_ARREADY;
    end else begin
        gmem2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op154_read_state12 == 1'b1))) begin
        gmem2_blk_n_R = m_axi_gmem2_RVALID;
    end else begin
        gmem2_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem3_blk_n_AW = m_axi_gmem3_AWREADY;
    end else begin
        gmem3_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem3_blk_n_B = m_axi_gmem3_BVALID;
    end else begin
        gmem3_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem3_blk_n_W = m_axi_gmem3_WREADY;
    end else begin
        gmem3_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp158))) begin
        grp_hf_add_f32_fu_686_ap_ce = 1'b1;
    end else begin
        grp_hf_add_f32_fu_686_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op146_readreq_state4 == 1'b1))) begin
        m_axi_gmem2_ARVALID = 1'b1;
    end else begin
        m_axi_gmem2_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op154_read_state12 == 1'b1))) begin
        m_axi_gmem2_RREADY = 1'b1;
    end else begin
        m_axi_gmem2_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem3_AWVALID = 1'b1;
    end else begin
        m_axi_gmem3_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem3_BREADY = 1'b1;
    end else begin
        m_axi_gmem3_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem3_WVALID = 1'b1;
    end else begin
        m_axi_gmem3_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln70_1_fu_757_p2 = (u_fu_232 + 4'd1);

assign add_ln70_fu_726_p2 = (ap_sig_allocacmp_indvar_flatten8_load + 7'd1);

assign add_ln71_fu_779_p2 = (select_ln70_fu_749_p3 + 4'd1);

assign add_ln77_fu_805_p2 = (zext_ln71_fu_802_p1 + tmp_9_fu_795_p3);

assign add_ln78_fu_815_p2 = ($signed(zext_ln77_fu_811_p1) + $signed(sext_ln70_cast_reg_1485));

assign add_ln85_fu_1117_p2 = ($signed(zext_ln77_fu_811_p1) + $signed(sext_ln70_1_cast_reg_1490));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage0_iter22)) | ((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln70_reg_1500_pp0_iter15_reg == 1'd0)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage0_iter22)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (m_axi_gmem3_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter16 == 1'b1) & ((icmp_ln70_reg_1500_pp0_iter15_reg == 1'd0) | (m_axi_gmem3_AWREADY == 1'b0))) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp158 = (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage0_iter22_ignore_call10)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (m_axi_gmem3_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter16 == 1'b1) & ((icmp_ln70_reg_1500_pp0_iter15_reg == 1'd0) | (m_axi_gmem3_AWREADY == 1'b0))) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11_ignore_call10)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

assign ap_block_pp0_stage0_ignoreCallOp158 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage0_iter22)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (m_axi_gmem3_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter16 == 1'b1) & ((icmp_ln70_reg_1500_pp0_iter15_reg == 1'd0) | (m_axi_gmem3_AWREADY == 1'b0))) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11 = ((ap_predicate_op154_read_state12 == 1'b1) & (m_axi_gmem2_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11_ignore_call10 = ((ap_predicate_op154_read_state12 == 1'b1) & (m_axi_gmem2_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state23_pp0_stage0_iter22 = (m_axi_gmem3_BVALID == 1'b0);
end

always @ (*) begin
    ap_block_state23_pp0_stage0_iter22_ignore_call10 = (m_axi_gmem3_BVALID == 1'b0);
end

always @ (*) begin
    ap_block_state4_io = ((ap_predicate_op146_readreq_state4 == 1'b1) & (m_axi_gmem2_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_764 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_initial_reg_674 = 'bx;

always @ (*) begin
    ap_predicate_op146_readreq_state4 = ((v26 == 1'd0) & (icmp_ln70_reg_1500_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op154_read_state12 = ((icmp_ln70_reg_1500_pp0_iter10_reg == 1'd0) & (v26 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign icmp_ln70_fu_720_p2 = ((ap_sig_allocacmp_indvar_flatten8_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_743_p2 = ((v_fu_228 == 4'd8) ? 1'b1 : 1'b0);

assign m_axi_gmem2_ARADDR = gmem2_addr_reg_1527;

assign m_axi_gmem2_ARBURST = 2'd0;

assign m_axi_gmem2_ARCACHE = 4'd0;

assign m_axi_gmem2_ARID = 1'd0;

assign m_axi_gmem2_ARLEN = 64'd1;

assign m_axi_gmem2_ARLOCK = 2'd0;

assign m_axi_gmem2_ARPROT = 3'd0;

assign m_axi_gmem2_ARQOS = 4'd0;

assign m_axi_gmem2_ARREGION = 4'd0;

assign m_axi_gmem2_ARSIZE = 3'd0;

assign m_axi_gmem2_ARUSER = 1'd0;

assign m_axi_gmem2_AWADDR = 64'd0;

assign m_axi_gmem2_AWBURST = 2'd0;

assign m_axi_gmem2_AWCACHE = 4'd0;

assign m_axi_gmem2_AWID = 1'd0;

assign m_axi_gmem2_AWLEN = 32'd0;

assign m_axi_gmem2_AWLOCK = 2'd0;

assign m_axi_gmem2_AWPROT = 3'd0;

assign m_axi_gmem2_AWQOS = 4'd0;

assign m_axi_gmem2_AWREGION = 4'd0;

assign m_axi_gmem2_AWSIZE = 3'd0;

assign m_axi_gmem2_AWUSER = 1'd0;

assign m_axi_gmem2_AWVALID = 1'b0;

assign m_axi_gmem2_BREADY = 1'b0;

assign m_axi_gmem2_WDATA = 32'd0;

assign m_axi_gmem2_WID = 1'd0;

assign m_axi_gmem2_WLAST = 1'b0;

assign m_axi_gmem2_WSTRB = 4'd0;

assign m_axi_gmem2_WUSER = 1'd0;

assign m_axi_gmem2_WVALID = 1'b0;

assign m_axi_gmem3_ARADDR = 64'd0;

assign m_axi_gmem3_ARBURST = 2'd0;

assign m_axi_gmem3_ARCACHE = 4'd0;

assign m_axi_gmem3_ARID = 1'd0;

assign m_axi_gmem3_ARLEN = 32'd0;

assign m_axi_gmem3_ARLOCK = 2'd0;

assign m_axi_gmem3_ARPROT = 3'd0;

assign m_axi_gmem3_ARQOS = 4'd0;

assign m_axi_gmem3_ARREGION = 4'd0;

assign m_axi_gmem3_ARSIZE = 3'd0;

assign m_axi_gmem3_ARUSER = 1'd0;

assign m_axi_gmem3_ARVALID = 1'b0;

assign m_axi_gmem3_AWADDR = gmem3_addr_reg_1538_pp0_iter15_reg;

assign m_axi_gmem3_AWBURST = 2'd0;

assign m_axi_gmem3_AWCACHE = 4'd0;

assign m_axi_gmem3_AWID = 1'd0;

assign m_axi_gmem3_AWLEN = 64'd1;

assign m_axi_gmem3_AWLOCK = 2'd0;

assign m_axi_gmem3_AWPROT = 3'd0;

assign m_axi_gmem3_AWQOS = 4'd0;

assign m_axi_gmem3_AWREGION = 4'd0;

assign m_axi_gmem3_AWSIZE = 3'd0;

assign m_axi_gmem3_AWUSER = 1'd0;

assign m_axi_gmem3_RREADY = 1'b0;

assign m_axi_gmem3_WDATA = v30_reg_1549;

assign m_axi_gmem3_WID = 1'd0;

assign m_axi_gmem3_WLAST = 1'b0;

assign m_axi_gmem3_WSTRB = 4'd15;

assign m_axi_gmem3_WUSER = 1'd0;

assign select_ln70_1_fu_763_p3 = ((icmp_ln71_fu_743_p2[0:0] == 1'b1) ? add_ln70_1_fu_757_p2 : u_fu_232);

assign select_ln70_fu_749_p3 = ((icmp_ln71_fu_743_p2[0:0] == 1'b1) ? 4'd0 : v_fu_228);

assign sext_ln70_1_cast_fu_698_p1 = $signed(sext_ln70_1);

assign sext_ln70_cast_fu_694_p1 = $signed(sext_ln70);

assign sext_ln78_fu_820_p1 = $signed(add_ln78_fu_815_p2);

assign sext_ln85_fu_1122_p1 = $signed(add_ln85_fu_1117_p2);

assign tmp_1_fu_861_p17 = 'bx;

assign tmp_2_fu_892_p17 = 'bx;

assign tmp_3_fu_923_p17 = 'bx;

assign tmp_4_fu_954_p17 = 'bx;

assign tmp_5_fu_985_p17 = 'bx;

assign tmp_6_fu_1016_p17 = 'bx;

assign tmp_7_fu_1047_p17 = 'bx;

assign tmp_9_fu_795_p3 = {{trunc_ln70_reg_1509}, {3'd0}};

assign tmp_fu_830_p17 = 'bx;

assign trunc_ln70_fu_771_p1 = select_ln70_1_fu_763_p3[2:0];

assign trunc_ln71_fu_775_p1 = select_ln70_fu_749_p3[2:0];

assign v26_read_read_fu_250_p2 = v26;

assign v27_fu_1132_p1 = m_axi_gmem2_RDATA;

assign v28_fu_1078_p17 = 'bx;

assign zext_ln71_fu_802_p1 = select_ln70_reg_1504;

assign zext_ln77_fu_811_p1 = add_ln77_fu_805_p2;

endmodule //gemm_fp32_gemm_fp32_Pipeline_l_outputs_u_l_v
