// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gemm_fp32_gemm_fp32_Pipeline_l_S_k_0_k_l_j (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        v1,
        v9_address0,
        v9_ce0,
        v9_we0,
        v9_d0,
        v9_address1,
        v9_ce1,
        v9_q1,
        sext_ln48
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [31:0] m_axi_gmem0_WDATA;
output  [3:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [31:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] v1;
output  [2:0] v9_address0;
output   v9_ce0;
output   v9_we0;
output  [31:0] v9_d0;
output  [2:0] v9_address1;
output   v9_ce1;
input  [31:0] v9_q1;
input  [61:0] sext_ln48;

reg ap_idle;
reg m_axi_gmem0_ARVALID;
reg m_axi_gmem0_RREADY;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_idle_pp0;
reg   [0:0] first_iter_0_reg_404;
reg    ap_block_state3_io;
reg   [0:0] first_iter_0_reg_404_pp0_iter9_reg;
reg    ap_block_state11_pp0_stage0_iter10;
reg   [0:0] icmp_ln48_reg_400;
reg   [0:0] icmp_ln48_reg_400_pp0_iter13_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter17_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln48_fu_192_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_R;
reg    gmem0_blk_n_AR;
reg    gmem0_blk_n_R;
reg    ap_block_pp0_stage0_11001;
wire  signed [62:0] sext_ln48_cast_fu_170_p1;
reg  signed [62:0] sext_ln48_cast_reg_385;
reg   [0:0] icmp_ln48_reg_400_pp0_iter1_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter2_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter3_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter4_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter5_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter6_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter7_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter8_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter9_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter10_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter11_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter12_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter14_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter15_reg;
reg   [0:0] icmp_ln48_reg_400_pp0_iter16_reg;
wire   [0:0] first_iter_0_fu_243_p2;
reg   [0:0] first_iter_0_reg_404_pp0_iter2_reg;
reg   [0:0] first_iter_0_reg_404_pp0_iter3_reg;
reg   [0:0] first_iter_0_reg_404_pp0_iter4_reg;
reg   [0:0] first_iter_0_reg_404_pp0_iter5_reg;
reg   [0:0] first_iter_0_reg_404_pp0_iter6_reg;
reg   [0:0] first_iter_0_reg_404_pp0_iter7_reg;
reg   [0:0] first_iter_0_reg_404_pp0_iter8_reg;
reg   [63:0] gmem0_addr_reg_408;
reg   [63:0] gmem1_addr_reg_414;
reg   [2:0] v9_addr_reg_420;
reg   [2:0] v9_addr_reg_420_pp0_iter2_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter3_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter4_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter5_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter6_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter7_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter8_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter9_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter10_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter11_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter12_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter13_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter14_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter15_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter16_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter17_reg;
reg   [2:0] v9_addr_reg_420_pp0_iter18_reg;
reg   [31:0] gmem1_addr_read_reg_426;
wire   [31:0] grp_hf_mul_f32_fu_156_ap_return;
reg   [31:0] v15_reg_441;
reg   [31:0] v17_reg_446;
wire   [31:0] grp_hf_add_f32_fu_163_ap_return;
reg   [31:0] v19_reg_451;
reg    grp_hf_mul_f32_fu_156_ap_ce;
wire   [31:0] grp_hf_mul_f32_fu_156_a;
wire   [31:0] grp_hf_mul_f32_fu_156_b;
wire   [0:0] grp_hf_mul_f32_fu_156_ap_ready_r;
reg    ap_block_state11_pp0_stage0_iter10_ignore_call15;
reg    ap_block_pp0_stage0_11001_ignoreCallOp95;
reg    grp_hf_add_f32_fu_163_ap_ce;
wire   [0:0] grp_hf_add_f32_fu_163_ap_ready_r;
reg    ap_block_state11_pp0_stage0_iter10_ignore_call18;
reg    ap_block_pp0_stage0_11001_ignoreCallOp101;
wire    ap_block_pp0_stage0_ignoreCallOp95;
wire    ap_block_pp0_stage0_ignoreCallOp101;
wire   [63:0] zext_ln49_fu_272_p1;
wire  signed [63:0] p_cast_fu_258_p1;
wire  signed [63:0] sext_ln52_fu_310_p1;
reg   [3:0] j_fu_80;
wire   [3:0] add_ln49_fu_320_p2;
wire    ap_loop_init;
reg   [3:0] k_fu_84;
wire   [3:0] select_ln48_1_fu_235_p3;
reg   [6:0] indvar_flatten_fu_88;
wire   [6:0] add_ln48_fu_198_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [31:0] gmem0_load1_fu_92;
reg    v9_ce1_local;
reg    v9_we0_local;
reg    v9_ce0_local;
wire   [0:0] icmp_ln49_fu_215_p2;
wire   [3:0] add_ln48_1_fu_229_p2;
wire   [3:0] select_ln48_fu_221_p3;
wire   [62:0] zext_ln48_fu_249_p1;
wire   [62:0] empty_fu_253_p2;
wire   [2:0] trunc_ln52_1_fu_277_p1;
wire   [2:0] trunc_ln52_fu_268_p1;
wire   [7:0] shl_ln1_fu_281_p4;
wire   [63:0] zext_ln52_fu_291_p1;
wire   [63:0] add_ln52_fu_295_p2;
wire   [61:0] trunc_ln52_2_fu_300_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 j_fu_80 = 4'd0;
#0 k_fu_84 = 4'd0;
#0 indvar_flatten_fu_88 = 7'd0;
#0 gmem0_load1_fu_92 = 32'd0;
#0 ap_done_reg = 1'b0;
end

hf_mul_f32 grp_hf_mul_f32_fu_156(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_hf_mul_f32_fu_156_ap_ce),
    .a(grp_hf_mul_f32_fu_156_a),
    .b(grp_hf_mul_f32_fu_156_b),
    .ap_ready(grp_hf_mul_f32_fu_156_ap_ready_r),
    .result(grp_hf_mul_f32_fu_156_ap_return)
);

hf_add_f32 grp_hf_add_f32_fu_163(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_hf_add_f32_fu_163_ap_ce),
    .a(v17_reg_446),
    .b(v15_reg_441),
    .ap_ready(grp_hf_add_f32_fu_163_ap_ready_r),
    .result(grp_hf_add_f32_fu_163_ap_return)
);

gemm_fp32_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln48_fu_192_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_88 <= add_ln48_fu_198_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_88 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_80 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_80 <= add_ln49_fu_320_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_84 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            k_fu_84 <= select_ln48_1_fu_235_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        first_iter_0_reg_404_pp0_iter2_reg <= first_iter_0_reg_404;
        first_iter_0_reg_404_pp0_iter3_reg <= first_iter_0_reg_404_pp0_iter2_reg;
        first_iter_0_reg_404_pp0_iter4_reg <= first_iter_0_reg_404_pp0_iter3_reg;
        first_iter_0_reg_404_pp0_iter5_reg <= first_iter_0_reg_404_pp0_iter4_reg;
        first_iter_0_reg_404_pp0_iter6_reg <= first_iter_0_reg_404_pp0_iter5_reg;
        first_iter_0_reg_404_pp0_iter7_reg <= first_iter_0_reg_404_pp0_iter6_reg;
        first_iter_0_reg_404_pp0_iter8_reg <= first_iter_0_reg_404_pp0_iter7_reg;
        first_iter_0_reg_404_pp0_iter9_reg <= first_iter_0_reg_404_pp0_iter8_reg;
        gmem1_addr_read_reg_426 <= m_axi_gmem1_RDATA;
        icmp_ln48_reg_400_pp0_iter10_reg <= icmp_ln48_reg_400_pp0_iter9_reg;
        icmp_ln48_reg_400_pp0_iter11_reg <= icmp_ln48_reg_400_pp0_iter10_reg;
        icmp_ln48_reg_400_pp0_iter12_reg <= icmp_ln48_reg_400_pp0_iter11_reg;
        icmp_ln48_reg_400_pp0_iter13_reg <= icmp_ln48_reg_400_pp0_iter12_reg;
        icmp_ln48_reg_400_pp0_iter14_reg <= icmp_ln48_reg_400_pp0_iter13_reg;
        icmp_ln48_reg_400_pp0_iter15_reg <= icmp_ln48_reg_400_pp0_iter14_reg;
        icmp_ln48_reg_400_pp0_iter16_reg <= icmp_ln48_reg_400_pp0_iter15_reg;
        icmp_ln48_reg_400_pp0_iter17_reg <= icmp_ln48_reg_400_pp0_iter16_reg;
        icmp_ln48_reg_400_pp0_iter2_reg <= icmp_ln48_reg_400_pp0_iter1_reg;
        icmp_ln48_reg_400_pp0_iter3_reg <= icmp_ln48_reg_400_pp0_iter2_reg;
        icmp_ln48_reg_400_pp0_iter4_reg <= icmp_ln48_reg_400_pp0_iter3_reg;
        icmp_ln48_reg_400_pp0_iter5_reg <= icmp_ln48_reg_400_pp0_iter4_reg;
        icmp_ln48_reg_400_pp0_iter6_reg <= icmp_ln48_reg_400_pp0_iter5_reg;
        icmp_ln48_reg_400_pp0_iter7_reg <= icmp_ln48_reg_400_pp0_iter6_reg;
        icmp_ln48_reg_400_pp0_iter8_reg <= icmp_ln48_reg_400_pp0_iter7_reg;
        icmp_ln48_reg_400_pp0_iter9_reg <= icmp_ln48_reg_400_pp0_iter8_reg;
        v15_reg_441 <= grp_hf_mul_f32_fu_156_ap_return;
        v19_reg_451 <= grp_hf_add_f32_fu_163_ap_return;
        v9_addr_reg_420_pp0_iter10_reg <= v9_addr_reg_420_pp0_iter9_reg;
        v9_addr_reg_420_pp0_iter11_reg <= v9_addr_reg_420_pp0_iter10_reg;
        v9_addr_reg_420_pp0_iter12_reg <= v9_addr_reg_420_pp0_iter11_reg;
        v9_addr_reg_420_pp0_iter13_reg <= v9_addr_reg_420_pp0_iter12_reg;
        v9_addr_reg_420_pp0_iter14_reg <= v9_addr_reg_420_pp0_iter13_reg;
        v9_addr_reg_420_pp0_iter15_reg <= v9_addr_reg_420_pp0_iter14_reg;
        v9_addr_reg_420_pp0_iter16_reg <= v9_addr_reg_420_pp0_iter15_reg;
        v9_addr_reg_420_pp0_iter17_reg <= v9_addr_reg_420_pp0_iter16_reg;
        v9_addr_reg_420_pp0_iter18_reg <= v9_addr_reg_420_pp0_iter17_reg;
        v9_addr_reg_420_pp0_iter2_reg <= v9_addr_reg_420;
        v9_addr_reg_420_pp0_iter3_reg <= v9_addr_reg_420_pp0_iter2_reg;
        v9_addr_reg_420_pp0_iter4_reg <= v9_addr_reg_420_pp0_iter3_reg;
        v9_addr_reg_420_pp0_iter5_reg <= v9_addr_reg_420_pp0_iter4_reg;
        v9_addr_reg_420_pp0_iter6_reg <= v9_addr_reg_420_pp0_iter5_reg;
        v9_addr_reg_420_pp0_iter7_reg <= v9_addr_reg_420_pp0_iter6_reg;
        v9_addr_reg_420_pp0_iter8_reg <= v9_addr_reg_420_pp0_iter7_reg;
        v9_addr_reg_420_pp0_iter9_reg <= v9_addr_reg_420_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_0_reg_404 <= first_iter_0_fu_243_p2;
        gmem0_addr_reg_408 <= p_cast_fu_258_p1;
        gmem1_addr_reg_414 <= sext_ln52_fu_310_p1;
        icmp_ln48_reg_400 <= icmp_ln48_fu_192_p2;
        icmp_ln48_reg_400_pp0_iter1_reg <= icmp_ln48_reg_400;
        sext_ln48_cast_reg_385 <= sext_ln48_cast_fu_170_p1;
        v9_addr_reg_420 <= zext_ln49_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_0_reg_404_pp0_iter9_reg == 1'd1))) begin
        gmem0_load1_fu_92 <= m_axi_gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v17_reg_446 <= v9_q1;
    end
end

always @ (*) begin
    if (((icmp_ln48_fu_192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_88;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (first_iter_0_reg_404 == 1'd1))) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (first_iter_0_reg_404_pp0_iter9_reg == 1'd1))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp101) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hf_add_f32_fu_163_ap_ce = 1'b1;
    end else begin
        grp_hf_add_f32_fu_163_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp95) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hf_mul_f32_fu_156_ap_ce = 1'b1;
    end else begin
        grp_hf_mul_f32_fu_156_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_0_reg_404 == 1'd1))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_0_reg_404_pp0_iter9_reg == 1'd1))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v9_ce0_local = 1'b1;
    end else begin
        v9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v9_ce1_local = 1'b1;
    end else begin
        v9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v9_we0_local = 1'b1;
    end else begin
        v9_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln48_1_fu_229_p2 = (k_fu_84 + 4'd1);

assign add_ln48_fu_198_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln49_fu_320_p2 = (select_ln48_fu_221_p3 + 4'd1);

assign add_ln52_fu_295_p2 = (zext_ln52_fu_291_p1 + v1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp_ln48_reg_400_pp0_iter17_reg == 1'd0)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (icmp_ln48_reg_400_pp0_iter13_reg == 1'd0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp101 = (((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp_ln48_reg_400_pp0_iter17_reg == 1'd0)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (icmp_ln48_reg_400_pp0_iter13_reg == 1'd0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10_ignore_call18)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp95 = (((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp_ln48_reg_400_pp0_iter17_reg == 1'd0)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (icmp_ln48_reg_400_pp0_iter13_reg == 1'd0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10_ignore_call15)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

assign ap_block_pp0_stage0_ignoreCallOp101 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp95 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp_ln48_reg_400_pp0_iter17_reg == 1'd0)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (icmp_ln48_reg_400_pp0_iter13_reg == 1'd0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10 = ((m_axi_gmem1_RVALID == 1'b0) | ((first_iter_0_reg_404_pp0_iter9_reg == 1'd1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10_ignore_call15 = ((m_axi_gmem1_RVALID == 1'b0) | ((first_iter_0_reg_404_pp0_iter9_reg == 1'd1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10_ignore_call18 = ((m_axi_gmem1_RVALID == 1'b0) | ((first_iter_0_reg_404_pp0_iter9_reg == 1'd1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmem1_ARREADY == 1'b0) | ((first_iter_0_reg_404 == 1'd1) & (m_axi_gmem0_ARREADY == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_253_p2 = ($signed(zext_ln48_fu_249_p1) + $signed(sext_ln48_cast_reg_385));

assign first_iter_0_fu_243_p2 = ((select_ln48_fu_221_p3 == 4'd0) ? 1'b1 : 1'b0);

assign grp_hf_mul_f32_fu_156_a = gmem0_load1_fu_92;

assign grp_hf_mul_f32_fu_156_b = gmem1_addr_read_reg_426;

assign icmp_ln48_fu_192_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_215_p2 = ((j_fu_80 == 4'd8) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARADDR = gmem0_addr_reg_408;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 64'd1;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 32'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 4'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_ARADDR = gmem1_addr_reg_414;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 64'd1;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 32'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 4'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign p_cast_fu_258_p1 = $signed(empty_fu_253_p2);

assign select_ln48_1_fu_235_p3 = ((icmp_ln49_fu_215_p2[0:0] == 1'b1) ? add_ln48_1_fu_229_p2 : k_fu_84);

assign select_ln48_fu_221_p3 = ((icmp_ln49_fu_215_p2[0:0] == 1'b1) ? 4'd0 : j_fu_80);

assign sext_ln48_cast_fu_170_p1 = $signed(sext_ln48);

assign sext_ln52_fu_310_p1 = $signed(trunc_ln52_2_fu_300_p4);

assign shl_ln1_fu_281_p4 = {{{trunc_ln52_1_fu_277_p1}, {trunc_ln52_fu_268_p1}}, {2'd0}};

assign trunc_ln52_1_fu_277_p1 = select_ln48_fu_221_p3[2:0];

assign trunc_ln52_2_fu_300_p4 = {{add_ln52_fu_295_p2[63:2]}};

assign trunc_ln52_fu_268_p1 = select_ln48_1_fu_235_p3[2:0];

assign v9_address0 = v9_addr_reg_420_pp0_iter18_reg;

assign v9_address1 = v9_addr_reg_420_pp0_iter12_reg;

assign v9_ce0 = v9_ce0_local;

assign v9_ce1 = v9_ce1_local;

assign v9_d0 = v19_reg_451;

assign v9_we0 = v9_we0_local;

assign zext_ln48_fu_249_p1 = select_ln48_1_fu_235_p3;

assign zext_ln49_fu_272_p1 = select_ln48_fu_221_p3;

assign zext_ln52_fu_291_p1 = shl_ln1_fu_281_p4;

endmodule //gemm_fp32_gemm_fp32_Pipeline_l_S_k_0_k_l_j
