// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gemm_fp32_gemm_fp32_Pipeline_l_S_k_0_k_l_j (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        BT_address0,
        BT_ce0,
        BT_q0,
        v9_address0,
        v9_ce0,
        v9_we0,
        v9_d0,
        v9_address1,
        v9_ce1,
        v9_q1,
        tmp_11,
        A_address0,
        A_ce0,
        A_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] BT_address0;
output   BT_ce0;
input  [31:0] BT_q0;
output  [2:0] v9_address0;
output   v9_ce0;
output   v9_we0;
output  [31:0] v9_d0;
output  [2:0] v9_address1;
output   v9_ce1;
input  [31:0] v9_q1;
input  [5:0] tmp_11;
output  [5:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln51_reg_331;
reg   [0:0] icmp_ln51_reg_331_pp0_iter6_reg;
reg   [0:0] icmp_ln51_reg_331_pp0_iter10_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln51_fu_160_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln51_reg_331_pp0_iter1_reg;
reg   [0:0] icmp_ln51_reg_331_pp0_iter2_reg;
reg   [0:0] icmp_ln51_reg_331_pp0_iter3_reg;
reg   [0:0] icmp_ln51_reg_331_pp0_iter4_reg;
reg   [0:0] icmp_ln51_reg_331_pp0_iter5_reg;
reg   [0:0] icmp_ln51_reg_331_pp0_iter7_reg;
reg   [0:0] icmp_ln51_reg_331_pp0_iter8_reg;
reg   [0:0] icmp_ln51_reg_331_pp0_iter9_reg;
wire   [3:0] select_ln51_fu_189_p3;
reg   [3:0] select_ln51_reg_335;
wire   [3:0] select_ln51_1_fu_203_p3;
reg   [3:0] select_ln51_1_reg_341;
wire   [0:0] first_iter_0_fu_211_p2;
reg   [0:0] first_iter_0_reg_346;
reg   [0:0] first_iter_0_reg_346_pp0_iter2_reg;
reg   [2:0] v9_addr_reg_360;
reg   [2:0] v9_addr_reg_360_pp0_iter3_reg;
reg   [2:0] v9_addr_reg_360_pp0_iter4_reg;
reg   [2:0] v9_addr_reg_360_pp0_iter5_reg;
reg   [2:0] v9_addr_reg_360_pp0_iter6_reg;
reg   [2:0] v9_addr_reg_360_pp0_iter7_reg;
reg   [2:0] v9_addr_reg_360_pp0_iter8_reg;
reg   [2:0] v9_addr_reg_360_pp0_iter9_reg;
reg   [2:0] v9_addr_reg_360_pp0_iter10_reg;
reg   [2:0] v9_addr_reg_360_pp0_iter11_reg;
reg   [31:0] BT_load_reg_366;
wire   [31:0] grp_hf_mul_f32_fu_128_ap_return;
reg   [31:0] v15_reg_381;
reg   [31:0] v17_reg_386;
wire   [31:0] grp_hf_add_f32_fu_135_ap_return;
reg   [31:0] v19_reg_391;
reg    grp_hf_mul_f32_fu_128_ap_ce;
wire   [31:0] grp_hf_mul_f32_fu_128_a;
wire   [31:0] grp_hf_mul_f32_fu_128_b;
wire   [0:0] grp_hf_mul_f32_fu_128_ap_ready_r;
reg    ap_block_pp0_stage0_11001_ignoreCallOp67;
reg    grp_hf_add_f32_fu_135_ap_ce;
wire   [0:0] grp_hf_add_f32_fu_135_ap_ready_r;
reg    ap_block_pp0_stage0_11001_ignoreCallOp73;
wire    ap_block_pp0_stage0_ignoreCallOp67;
wire    ap_block_pp0_stage0_ignoreCallOp73;
wire   [63:0] p_cast_fu_241_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln55_fu_267_p1;
wire   [63:0] zext_ln52_fu_246_p1;
reg   [3:0] j_fu_56;
wire   [3:0] add_ln52_fu_217_p2;
wire    ap_loop_init;
reg   [3:0] k_fu_60;
reg   [6:0] indvar_flatten_fu_64;
wire   [6:0] add_ln51_fu_166_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [31:0] A_load1_fu_68;
reg    A_ce0_local;
reg    BT_ce0_local;
reg    v9_ce1_local;
reg    v9_we0_local;
reg    v9_ce0_local;
wire   [0:0] icmp_ln52_fu_183_p2;
wire   [3:0] add_ln51_1_fu_197_p2;
wire   [5:0] zext_ln51_fu_233_p1;
wire   [5:0] empty_fu_236_p2;
wire   [2:0] trunc_ln55_fu_250_p1;
wire   [5:0] shl_ln_fu_253_p3;
wire   [5:0] add_ln55_fu_261_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 j_fu_56 = 4'd0;
#0 k_fu_60 = 4'd0;
#0 indvar_flatten_fu_64 = 7'd0;
#0 A_load1_fu_68 = 32'd0;
#0 ap_done_reg = 1'b0;
end

hf_mul_f32 grp_hf_mul_f32_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_hf_mul_f32_fu_128_ap_ce),
    .a(grp_hf_mul_f32_fu_128_a),
    .b(grp_hf_mul_f32_fu_128_b),
    .ap_ready(grp_hf_mul_f32_fu_128_ap_ready_r),
    .result(grp_hf_mul_f32_fu_128_ap_return)
);

hf_add_f32 grp_hf_add_f32_fu_135(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_hf_add_f32_fu_135_ap_ce),
    .a(v17_reg_386),
    .b(v15_reg_381),
    .ap_ready(grp_hf_add_f32_fu_135_ap_ready_r),
    .result(grp_hf_add_f32_fu_135_ap_return)
);

gemm_fp32_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln51_fu_160_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_64 <= add_ln51_fu_166_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_64 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_56 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_56 <= add_ln52_fu_217_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_60 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            k_fu_60 <= select_ln51_1_fu_203_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (first_iter_0_reg_346_pp0_iter2_reg == 1'd1))) begin
        A_load1_fu_68 <= A_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        BT_load_reg_366 <= BT_q0;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        first_iter_0_reg_346_pp0_iter2_reg <= first_iter_0_reg_346;
        icmp_ln51_reg_331_pp0_iter10_reg <= icmp_ln51_reg_331_pp0_iter9_reg;
        icmp_ln51_reg_331_pp0_iter2_reg <= icmp_ln51_reg_331_pp0_iter1_reg;
        icmp_ln51_reg_331_pp0_iter3_reg <= icmp_ln51_reg_331_pp0_iter2_reg;
        icmp_ln51_reg_331_pp0_iter4_reg <= icmp_ln51_reg_331_pp0_iter3_reg;
        icmp_ln51_reg_331_pp0_iter5_reg <= icmp_ln51_reg_331_pp0_iter4_reg;
        icmp_ln51_reg_331_pp0_iter6_reg <= icmp_ln51_reg_331_pp0_iter5_reg;
        icmp_ln51_reg_331_pp0_iter7_reg <= icmp_ln51_reg_331_pp0_iter6_reg;
        icmp_ln51_reg_331_pp0_iter8_reg <= icmp_ln51_reg_331_pp0_iter7_reg;
        icmp_ln51_reg_331_pp0_iter9_reg <= icmp_ln51_reg_331_pp0_iter8_reg;
        v15_reg_381 <= grp_hf_mul_f32_fu_128_ap_return;
        v19_reg_391 <= grp_hf_add_f32_fu_135_ap_return;
        v9_addr_reg_360 <= zext_ln52_fu_246_p1;
        v9_addr_reg_360_pp0_iter10_reg <= v9_addr_reg_360_pp0_iter9_reg;
        v9_addr_reg_360_pp0_iter11_reg <= v9_addr_reg_360_pp0_iter10_reg;
        v9_addr_reg_360_pp0_iter3_reg <= v9_addr_reg_360;
        v9_addr_reg_360_pp0_iter4_reg <= v9_addr_reg_360_pp0_iter3_reg;
        v9_addr_reg_360_pp0_iter5_reg <= v9_addr_reg_360_pp0_iter4_reg;
        v9_addr_reg_360_pp0_iter6_reg <= v9_addr_reg_360_pp0_iter5_reg;
        v9_addr_reg_360_pp0_iter7_reg <= v9_addr_reg_360_pp0_iter6_reg;
        v9_addr_reg_360_pp0_iter8_reg <= v9_addr_reg_360_pp0_iter7_reg;
        v9_addr_reg_360_pp0_iter9_reg <= v9_addr_reg_360_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_0_reg_346 <= first_iter_0_fu_211_p2;
        icmp_ln51_reg_331 <= icmp_ln51_fu_160_p2;
        icmp_ln51_reg_331_pp0_iter1_reg <= icmp_ln51_reg_331;
        select_ln51_1_reg_341 <= select_ln51_1_fu_203_p3;
        select_ln51_reg_335 <= select_ln51_fu_189_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        v17_reg_386 <= v9_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        BT_ce0_local = 1'b1;
    end else begin
        BT_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_160_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp73) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hf_add_f32_fu_135_ap_ce = 1'b1;
    end else begin
        grp_hf_add_f32_fu_135_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp67) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hf_mul_f32_fu_128_ap_ce = 1'b1;
    end else begin
        grp_hf_mul_f32_fu_128_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        v9_ce0_local = 1'b1;
    end else begin
        v9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        v9_ce1_local = 1'b1;
    end else begin
        v9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        v9_we0_local = 1'b1;
    end else begin
        v9_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = p_cast_fu_241_p1;

assign A_ce0 = A_ce0_local;

assign BT_address0 = zext_ln55_fu_267_p1;

assign BT_ce0 = BT_ce0_local;

assign add_ln51_1_fu_197_p2 = (k_fu_60 + 4'd1);

assign add_ln51_fu_166_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln52_fu_217_p2 = (select_ln51_fu_189_p3 + 4'd1);

assign add_ln55_fu_261_p2 = (shl_ln_fu_253_p3 + zext_ln51_fu_233_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln51_reg_331_pp0_iter10_reg == 1'd0) & (ap_enable_reg_pp0_iter11 == 1'b1)) | ((icmp_ln51_reg_331_pp0_iter6_reg == 1'd0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp67 = (((icmp_ln51_reg_331_pp0_iter10_reg == 1'd0) & (ap_enable_reg_pp0_iter11 == 1'b1)) | ((icmp_ln51_reg_331_pp0_iter6_reg == 1'd0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp73 = (((icmp_ln51_reg_331_pp0_iter10_reg == 1'd0) & (ap_enable_reg_pp0_iter11 == 1'b1)) | ((icmp_ln51_reg_331_pp0_iter6_reg == 1'd0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

assign ap_block_pp0_stage0_ignoreCallOp67 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp73 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln51_reg_331_pp0_iter10_reg == 1'd0) & (ap_enable_reg_pp0_iter11 == 1'b1)) | ((icmp_ln51_reg_331_pp0_iter6_reg == 1'd0) & (ap_enable_reg_pp0_iter7 == 1'b1)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_236_p2 = (zext_ln51_fu_233_p1 + tmp_11);

assign first_iter_0_fu_211_p2 = ((select_ln51_fu_189_p3 == 4'd0) ? 1'b1 : 1'b0);

assign grp_hf_mul_f32_fu_128_a = A_load1_fu_68;

assign grp_hf_mul_f32_fu_128_b = BT_load_reg_366;

assign icmp_ln51_fu_160_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_183_p2 = ((j_fu_56 == 4'd8) ? 1'b1 : 1'b0);

assign p_cast_fu_241_p1 = empty_fu_236_p2;

assign select_ln51_1_fu_203_p3 = ((icmp_ln52_fu_183_p2[0:0] == 1'b1) ? add_ln51_1_fu_197_p2 : k_fu_60);

assign select_ln51_fu_189_p3 = ((icmp_ln52_fu_183_p2[0:0] == 1'b1) ? 4'd0 : j_fu_56);

assign shl_ln_fu_253_p3 = {{trunc_ln55_fu_250_p1}, {3'd0}};

assign trunc_ln55_fu_250_p1 = select_ln51_reg_335[2:0];

assign v9_address0 = v9_addr_reg_360_pp0_iter11_reg;

assign v9_address1 = v9_addr_reg_360_pp0_iter5_reg;

assign v9_ce0 = v9_ce0_local;

assign v9_ce1 = v9_ce1_local;

assign v9_d0 = v19_reg_391;

assign v9_we0 = v9_we0_local;

assign zext_ln51_fu_233_p1 = select_ln51_1_reg_341;

assign zext_ln52_fu_246_p1 = select_ln51_reg_335;

assign zext_ln55_fu_267_p1 = add_ln55_fu_261_p2;

endmodule //gemm_fp32_gemm_fp32_Pipeline_l_S_k_0_k_l_j
